<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUAR_1_2_3</name>
   <tag></tag>
   <elementGuidId>0ab9fc86-7921-40d1-98dd-43fc0a0dcf48</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#avanzarListarEnvios</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='avanzarListarEnvios']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>09e57920-51c6-43f9-a898-c3f040caf5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>avanzarListarEnvios</value>
      <webElementGuid>14e02fb1-4663-405f-9742-8b46cf37fc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 custom-btn boton</value>
      <webElementGuid>4c3d5522-05b7-4ba7-a343-52a5ec9676af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>2974e4ce-a65f-49ec-a627-43a214882834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>36e81a4e-784a-41f1-997e-0ddf8e4dae34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avanzarListarEnvios&quot;)</value>
      <webElementGuid>55ae6e7f-12f7-47bc-82d3-54ccd2c0f83a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='avanzarListarEnvios']</value>
      <webElementGuid>f97033b3-19fc-4550-a192-689e08fa2f61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[4]/button[2]</value>
      <webElementGuid>d41d466c-9d0a-47b3-9187-35acfc3d5f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[2]/following::button[1]</value>
      <webElementGuid>ecb26460-c7d8-4c3c-bede-d04bfc1ab4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/following::button[2]</value>
      <webElementGuid>5015a906-a0f8-4176-85a3-b13794411c78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'avanzarListarEnvios', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>3eb39ea1-20fc-40ef-ba37-455098459dea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]</value>
      <webElementGuid>71e2a0fc-bc4c-47e2-86c7-9fe53e111bfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'avanzarListarEnvios' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>4540f659-4c0c-4a92-a5b5-db94adb7ebba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
