<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Completa los datos de la persona que _27237c</name>
   <tag></tag>
   <elementGuidId>ccff2391-4597-45be-a674-9db28d442fca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputNroDocumentoConsignado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputNroDocumentoConsignado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fe447053-7471-4bf1-a905-785f154f8759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8f3b1186-8256-42e8-abdd-eaef0717408c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputNroDocumentoConsignado</value>
      <webElementGuid>8ed12e74-a87a-472c-878a-d63e2454c383</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputNroDocumentoConsignado</value>
      <webElementGuid>bc5963fc-ed99-48ee-acfa-513ee3887a8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>75b5ef4d-4e80-4869-9a0b-5cd637a9ac60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>4fb0f9d9-16ba-4dc9-8076-2d8e766aa5e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>3d3cbf9a-35d0-4851-985c-a67c67ddef0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>a303d646-210a-40bf-8a27-26e1b92e2d32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputNroDocumentoConsignado</value>
      <webElementGuid>34b7e9bc-c234-4cb1-9336-5310c1690f1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>8</value>
      <webElementGuid>bd161214-9450-442d-9709-d186195d6e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputNroDocumentoConsignado&quot;)</value>
      <webElementGuid>ec51ffd0-7ed6-4d45-918c-71916480a534</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputNroDocumentoConsignado']</value>
      <webElementGuid>20deea40-428c-4b6c-a230-a679a02848a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[3]/div[2]/div/input</value>
      <webElementGuid>62f45d36-8fe4-4d77-985c-d3e1f70c6b95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>93927bd3-2c78-419c-ab29-cdc79ee4b7f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputNroDocumentoConsignado']</value>
      <webElementGuid>daadea5a-0f7f-4648-b3bb-eac9a8925f80</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
