<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TIPO DE DOCUMENTO  DNI  RUC  C.E</name>
   <tag></tag>
   <elementGuidId>7062cb92-5c24-47ba-97e1-485b5d444015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tipoDocumentoConsignado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoDocumentoConsignado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9b022a6f-8208-4ff3-86e9-549bb0fd9587</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoDocumentoConsignado</value>
      <webElementGuid>9e188f9d-c733-4434-82a5-25086fa3294d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>tipoDocumentoConsignado</value>
      <webElementGuid>357e2da9-c422-4954-805a-ada77a373687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>tipoDocumentoConsignado</value>
      <webElementGuid>f6507727-80fd-485e-ad82-c65e3fa07556</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5b3e9f78-a903-4aee-8fd0-87dd17ca8726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>68865eb9-b4dc-4cfb-826c-2945f0b873a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> TIPO DE DOCUMENTO  DNI  RUC  C.E. </value>
      <webElementGuid>9a09aba7-81a3-468a-b91f-12224e6dcacb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoDocumentoConsignado&quot;)</value>
      <webElementGuid>6d4b9e54-bafd-4de4-911c-7d700f9cb613</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoDocumentoConsignado']</value>
      <webElementGuid>37fd03ae-ca58-48b1-99e1-de6f00da2b41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[3]/div/select</value>
      <webElementGuid>01841484-2549-4ec9-8da1-40627f83476e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completa los datos de la persona que recibirá tu envío.'])[1]/following::select[1]</value>
      <webElementGuid>3bb9d856-9dd0-4bcf-b475-7c6c44df732d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de quién recibe'])[1]/following::select[1]</value>
      <webElementGuid>c29778ce-0950-4135-b85e-0e3e27ab6207</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NÚMERO DOCUMENTO'])[1]/preceding::select[1]</value>
      <webElementGuid>dc879fd0-10d4-4350-b36d-5768a07753dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOMBRES(S)'])[1]/preceding::select[1]</value>
      <webElementGuid>d76236e6-9660-4f99-bd7a-006a854fff4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>016f2230-b199-424e-9eae-4ac33b7d06ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoDocumentoConsignado' and (text() = ' TIPO DE DOCUMENTO  DNI  RUC  C.E. ' or . = ' TIPO DE DOCUMENTO  DNI  RUC  C.E. ')]</value>
      <webElementGuid>11cba7ae-74f4-4079-b7be-7b2455394393</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
