<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_mercancias peligrosas_slider round</name>
   <tag></tag>
   <elementGuidId>f1209674-9bd3-4c1c-bc3c-718894511a81</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.switch.dismiss-responsive-1 > span.slider.round</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[8]/div/div/label/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>47becc0b-9641-449c-a2d8-ffe0f5d771e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider round</value>
      <webElementGuid>d0d7099f-6f64-47aa-a055-11f61707898d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[1]/app-formulario-envio[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row px-4 pxc&quot;]/div[@class=&quot;col-personalized-2&quot;]/div[@class=&quot;shadow border-card contenedor-div&quot;]/div[@class=&quot;row ng-invalid ng-star-inserted ng-dirty ng-touched&quot;]/div[@class=&quot;col-md-12 mt-1 relative-position-show&quot;]/div[@class=&quot;d-flex align-items-center input-container&quot;]/div[1]/label[@class=&quot;switch dismiss-responsive-1&quot;]/span[@class=&quot;slider round&quot;]</value>
      <webElementGuid>cc7fd8f1-0d75-4f7e-a8ae-7d0be98ae63f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[8]/div/div/label/span</value>
      <webElementGuid>e4605c7d-6199-46f9-b9bc-efb133a2e486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div/label/span</value>
      <webElementGuid>fcfbf7c7-7b40-4d41-8d2b-cdab3f18e741</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
