<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continuar (1)</name>
   <tag></tag>
   <elementGuidId>e789dc6e-16e3-40af-b636-f2e4debb9224</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-continue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payment-continue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Continuar&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5884da98-b42a-4875-adca-12884ec7a0cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-continue</value>
      <webElementGuid>7ec474a6-f81d-4c3d-bd50-7830e2d92a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-control btn btn-submit btn-success btn-block j-secure-form-payment-method btn-pay btn-decorator</value>
      <webElementGuid>5ba0b311-a5fe-495c-ab4e-4cc6a305953d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b2fe25d5-a7d1-4d55-af26-8d571a709c77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>9a21abbb-448c-49fd-98ce-29666a528c58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-continue&quot;)</value>
      <webElementGuid>744eae9f-5c12-40c4-aca3-721023ce3e56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ValidarPagoDenegado/Page_Registro de Envos/iframe_concat(id(, , visaNetJS, , ))_visaNetJS</value>
      <webElementGuid>c8ef4687-c75c-4fd7-adbc-2569d1803ecd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='payment-continue']</value>
      <webElementGuid>17ed2a0c-479e-4d50-b0e5-d1ae5b7740f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethods']/div/div/section/button</value>
      <webElementGuid>95e0eb46-534e-43c6-83c3-8b95b62e9b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago con Yape'])[1]/following::button[1]</value>
      <webElementGuid>e6c6a78a-02cc-4766-af48-12a502fa4fa3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago con Puntos/Millas'])[1]/following::button[1]</value>
      <webElementGuid>c26c5693-c41e-40fa-a12c-b17ba5973e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Cómo realizar tu compra con PagoEfectivo?'])[1]/preceding::button[1]</value>
      <webElementGuid>cdaa7bff-d3e1-496e-981b-5f387db2319c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✓ Depósitos en efectivo vía PagoEfectivo'])[1]/preceding::button[1]</value>
      <webElementGuid>8d3cfdec-d0c4-4e12-a9f1-c281e39fcbd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuar']/parent::*</value>
      <webElementGuid>72b87107-fb97-4563-b53e-813d0e6a69fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>6a2681a1-842e-4f6c-831f-1979732bf5f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'payment-continue' and @type = 'button' and (text() = 'Continuar' or . = 'Continuar')]</value>
      <webElementGuid>c1486ee4-d8da-4e9d-b611-2ff5ff67f0df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
