<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Tarjeta de crditodbito,billeteras electrnicas</name>
   <tag></tag>
   <elementGuidId>6ea88e1a-8244-4dea-8f74-4c731a7e00c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonPagarNiubiz</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttonPagarNiubiz']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#buttonPagarNiubiz</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>fb8cc804-f809-4015-81ae-318d95ea4cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonPagarNiubiz</value>
      <webElementGuid>9f6e51af-d9ea-4fa1-90af-abc61e33e6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>payment-methods justify-content-center align-items-center div-tipo-pago-small-purple ng-star-inserted</value>
      <webElementGuid>264b073d-2570-4c9b-86a1-7f2ccddc94e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tarjeta de crédito/débito,billeteras electrónicas.</value>
      <webElementGuid>229b9da8-9924-4c83-bd93-5d05e872e954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonPagarNiubiz&quot;)</value>
      <webElementGuid>61c66443-fdfa-4bac-af22-062f52979966</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='buttonPagarNiubiz']</value>
      <webElementGuid>63dff39d-f0dd-4a7f-9533-f9e1c3b8c8ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>b64b6168-0c20-46e9-b6b9-a3da373d7bb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elige la opción de tu preferencia y recuerda que todos nuestros medios de pago son seguros.'])[1]/following::div[3]</value>
      <webElementGuid>9070a75e-3376-4782-ac92-a0893ffb3d2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Elige tu medio de pago preferido'])[1]/following::div[3]</value>
      <webElementGuid>e4bb88c6-b0ef-44da-b78a-5870433d5759</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div</value>
      <webElementGuid>c213818e-fe3b-423b-87d5-110c2a4c5fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'buttonPagarNiubiz' and (text() = 'Tarjeta de crédito/débito,billeteras electrónicas.' or . = 'Tarjeta de crédito/débito,billeteras electrónicas.')]</value>
      <webElementGuid>ade5160c-28f0-4a94-b16d-32ef725bccfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
