<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_REGISTRO DENEGADO_img-fluid</name>
   <tag></tag>
   <elementGuidId>e5f7fdf3-0649-477f-9c36-f75d1aab9090</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.shadow.border-card.contenedor-div.border-respuesta-responsive > div > img.img-fluid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/main/app-denegado-niubiz/div[2]/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#content div >> internal:has-text=&quot;¡REGISTRO DENEGADO! N° de Registro 202506728370Ingrese correctamente las credenc&quot;i >> internal:role=img >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>72a82574-92de-4e3c-987a-76886853ec13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icon_alert_circle_red.png</value>
      <webElementGuid>1ba61515-6b1b-4dd1-80bd-ebd58b70fbe3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>c7973b42-778f-4b98-8b3e-f856065b6e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>30</value>
      <webElementGuid>9ab084cd-277e-41c7-9762-e9c7167ec656</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>1b3df185-6d90-4247-a89f-ccb9c14ed169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[1]/app-denegado-niubiz[1]/div[@class=&quot;shadow border-card contenedor-div border-respuesta-responsive&quot;]/div[1]/img[@class=&quot;img-fluid&quot;]</value>
      <webElementGuid>a40b0210-a785-4386-a67c-ac430e20c661</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-denegado-niubiz/div[2]/div/img</value>
      <webElementGuid>a48e3bed-f1ef-463a-94a6-ad4d11ee8ba8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/img</value>
      <webElementGuid>a4cf0435-0f2a-46c5-8dc4-511184a7a5f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/icon_alert_circle_red.png']</value>
      <webElementGuid>74450039-dbb9-4fcc-b151-255db741b7d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
