<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_compras por internet_cvc</name>
   <tag></tag>
   <elementGuidId>68239170-c09e-4739-91c9-1b899c450c9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cvc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cvc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#cvc</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f07401af-cafb-4c03-98b3-23e1bdfe12b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>848804e5-2c4d-4915-b4f4-79f9c06ed4e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvc</value>
      <webElementGuid>a7a928c1-c0aa-4b7c-aee0-6bb5d7b96d04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cvc</value>
      <webElementGuid>2f2a51f3-9de3-459e-958b-fce1c16bc6da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlenght</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>eb4c2e43-27c3-42eb-a685-95893c124772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cvv-security text-security</value>
      <webElementGuid>b7e24d4c-fef0-424b-b286-345ab433f41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>f0295fa5-6b7e-4c97-afd2-39f299fdf742</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CVV</value>
      <webElementGuid>b6f66878-fa8b-4c0e-bb21-d6096d999464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvc&quot;)</value>
      <webElementGuid>4e25fd02-aedf-49d7-9b18-ff8819e208f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/ValidarPagoDenegado/Page_Registro de Envos/iframe_concat(id(, , visaNetJS, , ))_visaNetJS</value>
      <webElementGuid>54949039-f8a1-499b-930b-8a6ab8e0505b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cvc']</value>
      <webElementGuid>858a787e-4f86-4744-b14b-fbeb6879197a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='default']/div[5]/div[3]/section/label/input</value>
      <webElementGuid>acf11c2e-72b7-4f2c-91a3-3b9619088779</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/section/label/input</value>
      <webElementGuid>510f2eb8-ea24-4cef-960a-0f6294108c3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'cvc' and @id = 'cvc' and @placeholder = 'CVV']</value>
      <webElementGuid>81f000d5-50e5-410e-a60f-36b1bcf8b262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
