<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TIPO DE ARTCULO  ACCESORIOS Y EQUIPO_f94c1d</name>
   <tag></tag>
   <elementGuidId>7181c258-7b72-4b3a-b4c6-e765b9896c62</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tipoArticulo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoArticulo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tipoArticulo</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7522ef2f-de2e-4e72-abb1-ebb808919fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoArticulo</value>
      <webElementGuid>c6f1d12e-362d-4d5c-8efb-1c7c6aaabe27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>tipoArticulo</value>
      <webElementGuid>66987e89-5e88-49c2-ba82-432072e0368e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-size ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>bda4eafb-d36c-4b86-a3f7-dfc570e32b5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>tipoArticulo</value>
      <webElementGuid>b071391d-0361-4ddb-848d-7e765ec38e2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>9d402148-f8c1-4764-aac5-aff7ed82897f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>308dd5e2-4d54-41ff-9580-4db8484ac9b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> TIPO DE ARTÍCULO  ACCESORIOS Y EQUIPOS ELECTRONICOS  ACCESORIOS PARA FIESTAS  ARTÍCULOS DE LIMPIEZA  ARTÍCULOS PUBLICITARIOS  BISUTERIA  CAJA  TARJETAS PERSONALES  MUEBLES Y DECOHOGAR  FERRETERÍA Y CONSTRUCCIÓN  ALIMENTACION Y BEBIDAS  COSMETICOS  ELECTROHOGAR  JUGUETES  MATERIAL MEDICO  MEDICINAS  REPUESTOS  ROPA Y ACCESORIOS  VALIJA-DOCUMENTOS  UTILES DE ESCRITORIO  UTILES DE OFICINA </value>
      <webElementGuid>1071ba3f-af93-4531-aaec-c44d380ae95c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoArticulo&quot;)</value>
      <webElementGuid>f105959a-6079-4a7a-a068-72fcd12ff2d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoArticulo']</value>
      <webElementGuid>2a4978b2-799b-42e3-a131-96dada317281</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[5]/div/select</value>
      <webElementGuid>1ba79fb5-3dae-45ff-b6b6-41f9ed7282b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione un tipo de artículo'])[1]/following::select[1]</value>
      <webElementGuid>b73b1b30-a20e-4b57-8cfe-25d98b66abc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOBRE'])[1]/following::select[1]</value>
      <webElementGuid>a15384b2-3f98-40f4-89c4-98642267ac65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALOR DEL CONTENIDO'])[1]/preceding::select[1]</value>
      <webElementGuid>0d5df5c8-b7bb-40cc-b316-f6c7e4325714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESPECIFICAR ARTÍCULO'])[1]/preceding::select[1]</value>
      <webElementGuid>8651fd55-d080-4778-b177-b96c6cb13155</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>60a6eddc-5e32-49fa-96e8-10dbf89c5bc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoArticulo' and (text() = ' TIPO DE ARTÍCULO  ACCESORIOS Y EQUIPOS ELECTRONICOS  ACCESORIOS PARA FIESTAS  ARTÍCULOS DE LIMPIEZA  ARTÍCULOS PUBLICITARIOS  BISUTERIA  CAJA  TARJETAS PERSONALES  MUEBLES Y DECOHOGAR  FERRETERÍA Y CONSTRUCCIÓN  ALIMENTACION Y BEBIDAS  COSMETICOS  ELECTROHOGAR  JUGUETES  MATERIAL MEDICO  MEDICINAS  REPUESTOS  ROPA Y ACCESORIOS  VALIJA-DOCUMENTOS  UTILES DE ESCRITORIO  UTILES DE OFICINA ' or . = ' TIPO DE ARTÍCULO  ACCESORIOS Y EQUIPOS ELECTRONICOS  ACCESORIOS PARA FIESTAS  ARTÍCULOS DE LIMPIEZA  ARTÍCULOS PUBLICITARIOS  BISUTERIA  CAJA  TARJETAS PERSONALES  MUEBLES Y DECOHOGAR  FERRETERÍA Y CONSTRUCCIÓN  ALIMENTACION Y BEBIDAS  COSMETICOS  ELECTROHOGAR  JUGUETES  MATERIAL MEDICO  MEDICINAS  REPUESTOS  ROPA Y ACCESORIOS  VALIJA-DOCUMENTOS  UTILES DE ESCRITORIO  UTILES DE OFICINA ')]</value>
      <webElementGuid>e5ec5435-8f72-4677-8862-1cb1676f7520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
