<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_La quiero conocer</name>
   <tag></tag>
   <elementGuidId>18479d46-1b42-4fcd-957a-02ba7ae603fe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnRedirectNewRE</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnRedirectNewRE']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;¡La quiero conocer!&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>61ab4095-e49b-4f8c-af4b-4f0393a5cd73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button-reenviar-new</value>
      <webElementGuid>721f0a29-3fbd-4157-bc9c-c9020e39f4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnRedirectNewRE</value>
      <webElementGuid>2281616f-1322-49b7-90eb-0aaeefb87dde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>¡La quiero conocer!</value>
      <webElementGuid>69a4d174-b35d-4bfb-a761-70dbe33ee7bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnRedirectNewRE&quot;)</value>
      <webElementGuid>54258347-327c-4d3a-85e2-8f073860a833</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnRedirectNewRE']</value>
      <webElementGuid>da3ce335-c7eb-45a7-ac33-0c38092ba649</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/button</value>
      <webElementGuid>66ba125c-eed9-42a3-9749-dd0a2c1a100d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=', conoce nuestra nueva plataforma'])[1]/following::button[1]</value>
      <webElementGuid>73136966-02f4-441f-b626-788212113171</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¡Nos renovamos!'])[1]/following::button[1]</value>
      <webElementGuid>2c4b3438-9489-42d6-98a7-f51179ff44e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Regresar'])[1]/preceding::button[1]</value>
      <webElementGuid>aad09f2f-6ff2-46a4-8c1c-8a801da1d4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué deseas realizar hoy?'])[1]/preceding::button[1]</value>
      <webElementGuid>7c0e03b5-de9b-4ca5-83f7-58b04a1dc14c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='¡La quiero conocer!']/parent::*</value>
      <webElementGuid>de30901a-4c58-46e0-a3fd-62ea02627538</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>602e214c-8a48-4058-aca6-5de7a449647c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btnRedirectNewRE' and (text() = '¡La quiero conocer!' or . = '¡La quiero conocer!')]</value>
      <webElementGuid>67278395-cd32-45fc-83a3-e2a700cd0ac7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
