<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Escriba su primer apellido igual al d_19137b</name>
   <tag></tag>
   <elementGuidId>62b22021-5cf6-4b8b-b150-47de7753a0c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputConfirmApellido</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputConfirmApellido']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;APELLIDO PATERNO&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fc4b8726-05f9-4a7a-8232-188f4d66cd7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>bf1b0b57-d5a1-48b1-95be-f4f711b3f528</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d228413e-fe65-4c28-b32c-0f052efcfa89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputConfirmApellido</value>
      <webElementGuid>6b6705ad-7af6-4145-8602-f3e61dc5c522</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>1a88221a-93d5-4de7-80f1-9c1b8ed2e0ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>73ec7648-5975-4d9a-aec5-5b099ba9f071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputConfirmApellido&quot;)</value>
      <webElementGuid>b2e77aaa-fc5b-4fca-b0dc-4fc6f4b4d10c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputConfirmApellido']</value>
      <webElementGuid>5e1d440a-fa17-419c-8b10-36408cbcdabc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-validacion-apellido-modal/div/div/div[2]/div/input</value>
      <webElementGuid>1aa3d25e-c1ae-40ce-a48d-85570f5e14de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-validacion-apellido-modal/div/div/div[2]/div/input</value>
      <webElementGuid>e853f49f-2fce-4ca7-bf23-6cdf4f9b0731</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputConfirmApellido']</value>
      <webElementGuid>0f512779-f1d0-4d30-bf06-f6697872519a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
