<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No s el peso de mi envo</name>
   <tag></tag>
   <elementGuidId>7fbb5b29-d2df-445a-b215-95b00cecfe6b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonIngresarMedidas</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonIngresarMedidas']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6548bb9f-028f-4e93-b341-67bdec8d1d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonIngresarMedidas</value>
      <webElementGuid>2ddef90d-26e3-4be3-89b0-8b12e55d3dbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton-dimensiones font-11 x-3 button-dimension size-button-dimension-responsive button-position-responsive</value>
      <webElementGuid>7da429c6-f150-46a7-8e9a-b16a0253f9a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>936a5792-a1db-40bb-908c-2f9e16d8f059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No sé el peso de mi envío</value>
      <webElementGuid>4e3d1416-32f4-4163-982b-b4fb9265e0d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonIngresarMedidas&quot;)</value>
      <webElementGuid>a0b14e31-36bb-48e0-9bae-9a3fd88cd25f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonIngresarMedidas']</value>
      <webElementGuid>8664b565-2461-4e58-b5df-ed3ba1a22e4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[4]/button</value>
      <webElementGuid>908cada5-9cdb-4e79-988c-116f51fcb15d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='consolas, etc'])[1]/following::button[1]</value>
      <webElementGuid>e6273fbb-ebb7-4884-9f1f-6e36f724cd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops,'])[1]/following::button[1]</value>
      <webElementGuid>df2acc91-b1e8-4468-9d63-2ee1a7dac6c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tiene que seleccionar un paquete.'])[1]/preceding::button[1]</value>
      <webElementGuid>d03c217a-a750-495d-8a83-eb8002aa9bfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>67c1ee90-105c-434e-bf5e-bcd394d5e648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonIngresarMedidas' and (text() = 'No sé el peso de mi envío' or . = 'No sé el peso de mi envío')]</value>
      <webElementGuid>669ff84e-fa9f-4373-bbeb-b233a36ebc59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
