<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_VOLVER_1</name>
   <tag></tag>
   <elementGuidId>0ae479f4-8df2-4944-9f4c-265ce312c90f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#volverToSeccionOrigen</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='volverToSeccionOrigen']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>69b87282-3786-442a-92d1-83a14766f995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>volverToSeccionOrigen</value>
      <webElementGuid>05d5e57f-5b3b-4925-90ce-58b3a1d337bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondary-boton px-3 me-2</value>
      <webElementGuid>5d8770b3-4314-4a8c-a49e-71bd27f3bcf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VOLVER</value>
      <webElementGuid>b599a2dc-b78c-44ac-8840-f676c37eae0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;volverToSeccionOrigen&quot;)</value>
      <webElementGuid>b6efa58c-ae48-4abc-9e7f-55f2d95f4ddf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='volverToSeccionOrigen']</value>
      <webElementGuid>b15b4dbc-52be-431f-9912-57dab3e9f86e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-que-envias/div/div[7]/button</value>
      <webElementGuid>5279d240-169a-4b00-9c96-50c4b5ff075d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pagar en línea.'])[1]/following::button[1]</value>
      <webElementGuid>538aa438-8169-42fa-9e0b-a8f0eda8b9fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[2]/preceding::button[1]</value>
      <webElementGuid>22d2f520-b18c-4b02-82c6-99da98a9d0cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[2]/preceding::button[2]</value>
      <webElementGuid>d75e803a-984b-4c77-b40c-96d55d4a7ed8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VOLVER']/parent::*</value>
      <webElementGuid>2599d734-8a0e-43f7-8736-0d98288c9bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button</value>
      <webElementGuid>48f92122-9371-42c0-b85d-7738f895a489</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'volverToSeccionOrigen' and (text() = 'VOLVER' or . = 'VOLVER')]</value>
      <webElementGuid>f0c3bcf1-f3d9-4565-8d3b-c1dd11e857c5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
