<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_REALIZAR UN ENVO</name>
   <tag></tag>
   <elementGuidId>3fde4546-588e-472d-9608-713d1781efb4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonEnvio</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttonEnvio']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4a844ad4-e92c-43bb-b751-672318562e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonEnvio</value>
      <webElementGuid>f5e5c446-1e71-4787-8ac2-70052d8d1b1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-card px-4 pb-3 ptc-4 text-center border rounded-10 shadow-sm back-color-orange</value>
      <webElementGuid>ce0ecacd-ac1e-43c3-9a07-e4ca4c9cf84c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REALIZAR UN ENVÍO</value>
      <webElementGuid>b677d124-c47e-4976-b166-062818dfa6cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonEnvio&quot;)</value>
      <webElementGuid>41b12cbf-673c-4a38-a293-0581bfba23da</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='buttonEnvio']</value>
      <webElementGuid>3e2cf3c6-6e2a-40c2-97b7-bb774623f02f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-principal/div/div[2]/div/div/div</value>
      <webElementGuid>901b2e57-893a-4cf8-bd92-fd2bdcca16bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué deseas realizar hoy?'])[1]/following::div[3]</value>
      <webElementGuid>eae764b1-d17d-4e75-989e-8e3f0ecd59d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>2a31c35c-9e3f-4142-92a2-b2bb38b29d44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'buttonEnvio' and (text() = 'REALIZAR UN ENVÍO' or . = 'REALIZAR UN ENVÍO')]</value>
      <webElementGuid>f367119f-6751-4e7c-96de-1c4614f988eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
