<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Qu deseas realizar hoy_icon mb-2</name>
   <tag></tag>
   <elementGuidId>f1f3b4bb-cc27-41a9-8d2a-ecc5fb8eed85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.icon.mb-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttonEnvio']/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>25d0df2f-504c-43eb-9b04-b73054836036</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>icon mb-2</value>
      <webElementGuid>67de58be-ed03-4cdb-b264-da53eee2a85e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonEnvio&quot;)/div[@class=&quot;icon mb-2&quot;]</value>
      <webElementGuid>9740879c-afd8-4eda-bcc7-c436a0ee731e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='buttonEnvio']/div</value>
      <webElementGuid>3bd157b1-f145-43a9-8830-4351c64223c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué deseas realizar hoy?'])[1]/following::div[4]</value>
      <webElementGuid>eb366dca-7d41-470d-ac57-0a8a9db61869</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>f9cd0132-0e0a-45f8-83ba-2e80730d4500</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
