<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Aceptar</name>
   <tag></tag>
   <elementGuidId>b9315cc9-b827-4646-8416-9f6ceda6e0ed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aceptarValorado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aceptarValorado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9653e50b-496a-4ef8-b5a4-fc7c89ed5f4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aceptarValorado</value>
      <webElementGuid>e92c1a80-efca-4080-8d7d-bfe6d95b2f35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>border-grey-light</value>
      <webElementGuid>1ad51252-3116-4d86-b476-333d9bbfc19e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>32f941fe-a4ef-40d0-a7b9-41145c0ff510</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aceptarValorado&quot;)</value>
      <webElementGuid>4d8c56f9-1aa8-48a8-b69f-cc631df45671</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aceptarValorado']</value>
      <webElementGuid>a38b87ec-7246-4780-a684-d5d88b550e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-alerta-valorado/div/div/div[2]/div[2]</value>
      <webElementGuid>03936ed0-5063-4720-aec8-e45d265aa3d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar envío'])[1]/following::div[1]</value>
      <webElementGuid>2487dd07-57df-4189-a406-b52a0c43d544</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recojo en tienda no disponible'])[1]/following::div[4]</value>
      <webElementGuid>c3d9cb27-e76c-4f20-a40e-2651c0e90465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'aceptarValorado', '&quot;', ')')])[1]/preceding::div[5]</value>
      <webElementGuid>e68e31e8-944e-4ff8-8b5c-e105c9a01483</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-alerta-valorado/div/div/div[2]/div[2]</value>
      <webElementGuid>0b8eb72d-c6d6-43fa-a012-fb611aef1405</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aceptarValorado' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>8dc7e2a0-ff27-4468-bb4c-01638f9ea0b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='aceptarValidacionApellido']</value>
      <webElementGuid>78248fe4-82e3-4235-bb04-782708739592</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-validacion-apellido-modal/div/div/div[3]/div[2]</value>
      <webElementGuid>f59504a5-6b2a-45f6-a5e4-b57957c77b5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::div[1]</value>
      <webElementGuid>161e8327-a561-4d65-b98b-c20003226b33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APELLIDO PATERNO'])[1]/following::div[3]</value>
      <webElementGuid>ba01f0b5-502e-4632-bc12-b6c0fd2afb72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'aceptarValidacionApellido', '&quot;', ')')])[1]/preceding::div[5]</value>
      <webElementGuid>55fb818f-8833-4135-b357-6017b3d18d9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-validacion-apellido-modal/div/div/div[3]/div[2]</value>
      <webElementGuid>46c028ab-c077-4e05-a94d-50c29b6d174d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'aceptarValidacionApellido' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>b2129686-fc60-4d18-a50d-bec6725f0fed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
