<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Consignado no encontrado</name>
   <tag></tag>
   <elementGuidId>80f132f7-f043-4235-a812-b0de5f232e94</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#swal2-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='swal2-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>a34e90e4-b9d5-4ef3-9134-3afd0b6895b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>0726a775-7fee-4dd3-bc48-c2e97969001a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>187e0bc2-2367-48d9-a8a4-3f15b653364e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Consignado no encontrado</value>
      <webElementGuid>a1d00931-dea2-4c2b-b0ed-9607527d6e11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-title&quot;)</value>
      <webElementGuid>f15dc271-3e6e-4bff-9475-50cbb35f1bb2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='swal2-title']</value>
      <webElementGuid>0291ba53-7f67-4f2e-b641-a6ab4597131a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::h2[1]</value>
      <webElementGuid>106ae329-d7e8-4574-8b3e-75f8085c6356</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'swal2-title', '&quot;', ')')])[1]/following::h2[1]</value>
      <webElementGuid>05f5f688-7c40-42fa-8696-9c616fbcff7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::h2[1]</value>
      <webElementGuid>5fd4bc61-ef7b-49c7-ba20-9ba7006114cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No'])[1]/preceding::h2[1]</value>
      <webElementGuid>b72dcb49-3c79-4727-b6e4-54bfc93ea9f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Consignado no encontrado']/parent::*</value>
      <webElementGuid>5d8abe9c-53b6-436e-a82d-b8234576a8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>d07a9ef0-4a6c-45d3-8930-c36465e5fa69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'swal2-title' and (text() = 'Consignado no encontrado' or . = 'Consignado no encontrado')]</value>
      <webElementGuid>cb99cf00-c3b5-44ec-a871-dff16f28b9e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
