<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>6b2a14fd-17c8-42c5-9f94-ef69347a46e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aceptarValorado > img</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='aceptarValorado']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>00023833-d040-4284-916d-fd01ac490e33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icon_accept_yellow.png</value>
      <webElementGuid>c023453c-f104-41be-898e-bcbd49df7a5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>c24705b6-2e4a-4f2f-9790-fd67d5a8dc27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>15</value>
      <webElementGuid>8f8b38af-c912-4898-b656-a1279b244c61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aceptarValorado&quot;)/img[1]</value>
      <webElementGuid>4d728400-2f1c-4fe1-804d-a48c2ab427ca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aceptarValorado']/img</value>
      <webElementGuid>9559fba5-96ed-47f7-bb16-beb55d7b61ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/img</value>
      <webElementGuid>66cafda8-ddf1-4867-8d57-d5fd0f01b9fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/icon_accept_yellow.png']</value>
      <webElementGuid>d8cb8915-1cfa-4204-beac-93276382a4eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
