<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_CONTINUAR_btn-icon_1</name>
   <tag></tag>
   <elementGuidId>12ad5439-d5de-4e82-b07a-bce9d82cdb72</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.btn-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='avanzarTipoArticulo']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b5b4a62d-568c-4e80-9121-f608164348f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icon_arrow_right.png</value>
      <webElementGuid>7d39731f-f754-4f73-a482-fc62ce019918</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e6c50dda-b0e1-4a14-8fa7-768ae7454673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>06dc5c4c-0ff7-4124-ad4a-2f7cfa4cffb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon</value>
      <webElementGuid>e9d1b9a0-1041-4731-be56-6c1ac6bb092a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avanzarTipoArticulo&quot;)/img[@class=&quot;btn-icon&quot;]</value>
      <webElementGuid>7df3321e-d181-4655-a5e8-cff75a84d6d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='avanzarTipoArticulo']/img</value>
      <webElementGuid>aad17609-a288-46e3-ad08-805f9157e188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/img</value>
      <webElementGuid>7edb45c6-c130-40c7-8cba-e5e7ca49b602</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/icon_arrow_right.png']</value>
      <webElementGuid>9aa46fd9-ca32-4ca8-a33c-514182ab3332</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
