<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NOMBRE(S)_inputApePatConsignadoComp</name>
   <tag></tag>
   <elementGuidId>6cdd9bbe-2398-456a-be88-c921920a2bf3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputApePatConsignadoComp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputApePatConsignadoComp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>186a3384-7691-447e-8c44-af2f256577ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>e7338df3-8c85-4142-a290-c9558b4c6156</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e327157-41ec-4450-9d20-2511970796b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputApePatConsignadoComp</value>
      <webElementGuid>c405b947-1057-46ff-b8d3-92be8abf8574</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputApePatConsignadoComp</value>
      <webElementGuid>1f28683d-d86e-43a8-abd0-bce1e1d40db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-pristine ng-touched ng-invalid</value>
      <webElementGuid>4e3e9d53-c339-4bda-90ea-05915298af5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>cd048f56-d451-4e9f-ac53-1dedb1d23efc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputApePatConsignadoComp</value>
      <webElementGuid>7e8f1c5c-7852-4510-8b33-232f8f14ed56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputApePatConsignadoComp&quot;)</value>
      <webElementGuid>c6c90e68-e2de-4ac8-8ca5-4a8247b105dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputApePatConsignadoComp']</value>
      <webElementGuid>2df02aec-3599-45b7-8fd0-d7e340de873a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-quien-recibe/div/div[3]/div[2]/div/input</value>
      <webElementGuid>9e62b89a-1fab-4f90-932f-47d16cbc2d5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/input</value>
      <webElementGuid>8fdbd0d6-74a0-474e-a888-8072710daa31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputApePatConsignadoComp']</value>
      <webElementGuid>8e0af6f9-e886-40f7-a056-8622fe26519d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
