<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_compras por internet_cvc</name>
   <tag></tag>
   <elementGuidId>126ded0e-0d95-417a-9d9b-8b5ab5cbf953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cvc</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='cvc']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2ae2105e-b011-4f5f-87a5-d85f0e769a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>aed654c5-0a6d-4dcf-9904-415408ddfc66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cvc</value>
      <webElementGuid>53d0037a-5c98-4768-a91c-cce727099941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cvc</value>
      <webElementGuid>26577110-1443-44dd-8973-af869ce62d1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlenght</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>de251e0f-57cf-4a2f-8af1-c92f954e493e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cvv-security text-security</value>
      <webElementGuid>97b1a2d9-c213-4922-b28f-75ea336587a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>b2a441f0-401c-4610-92ca-67acb1e244d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>CVV</value>
      <webElementGuid>4e259f14-3c31-4ab4-8f7a-8bfaaa4cf48f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cvc&quot;)</value>
      <webElementGuid>79fda960-21dd-4c67-8d83-f546bf29e450</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Negativos/camposVacios/iframe_Cancel_visaNetJS</value>
      <webElementGuid>0e9699e8-a932-46f1-971c-052e912cc0cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cvc']</value>
      <webElementGuid>5a68691a-f803-426e-a02f-91f06b4a9edc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='default']/div[5]/div[3]/section/label/input</value>
      <webElementGuid>7ebba95f-44ec-4d07-bd70-19c6b1e46f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/section/label/input</value>
      <webElementGuid>1aafd8c9-b240-4cec-9e55-412661d18ae7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'cvc' and @id = 'cvc' and @placeholder = 'CVV']</value>
      <webElementGuid>72bbd9ae-67e2-4c25-90b6-11db2e4c48eb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
