<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Impresoras, laptops, consolas, etc_se_20c89d</name>
   <tag></tag>
   <elementGuidId>86f75f7f-2bd6-4b53-a9a0-cdf9c4cc7a87</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectDestinoTienda</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectDestinoTienda']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b7e620d8-78c1-4e27-ad7d-69740d3af24e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d6835283-6e6e-4a57-b4d5-e4482eead7d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2ead48e4-6873-4714-a26e-f7abd73ec264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectDestinoTienda</value>
      <webElementGuid>b23f386a-f890-4894-bfa5-58b29307ae31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>selectDestinoTienda</value>
      <webElementGuid>d5481f68-b1d9-4675-9eca-f42f4c04c7fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>b536375d-d95a-4c5f-882d-791ac12a4f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>2d5a38f0-1c06-49eb-9fa4-3c8075b8b232</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>selectDestinoTienda</value>
      <webElementGuid>60d07681-295e-46f8-9b9b-0d3078da57c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectDestinoTienda&quot;)</value>
      <webElementGuid>2232d963-a33d-4da6-902a-8eea7eac7566</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectDestinoTienda']</value>
      <webElementGuid>922ad8f7-1467-439a-9ec9-41ddf5130a54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div/div/input</value>
      <webElementGuid>ee82fd95-829a-4fa2-8d82-f82036998907</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-cargo-adjunto/div/div/div[5]/div/div/input</value>
      <webElementGuid>bfcf71f9-f955-4f91-9e3a-59763958adfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'selectDestinoTienda']</value>
      <webElementGuid>738dd38f-64f7-4fd1-9580-afe04c396622</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/input</value>
      <webElementGuid>3000c7cd-d923-4a20-8920-1a7ff10f19e4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
