<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NMERO DOCUMENTO_inputCelularConsignadoComp</name>
   <tag></tag>
   <elementGuidId>b358b5ec-811a-4ad1-837e-2fd372ce409f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputCelularConsignadoComp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputCelularConsignadoComp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1fc9ac79-d3eb-4635-a643-68681f4c8601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8682615a-1894-4970-b019-8de9a04b1738</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputCelularConsignadoComp</value>
      <webElementGuid>641b07d2-cf45-4fef-84cc-bdc349b08d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputCelularConsignadoComp</value>
      <webElementGuid>8ef0cc78-4ec3-43a7-a11f-3b7411d73eb0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>1b3b5cf2-3a48-4437-892b-9bbad42fa980</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>9084e0f2-1f46-4048-b15b-21244989033e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>6f894cdc-e932-4db6-8a7f-5d1815621db6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-pristine ng-touched ng-invalid</value>
      <webElementGuid>95d5aa1d-601e-4126-a6d1-be8ceed96498</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>b110a328-b1cb-471c-ab20-987320893b7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-pattern</name>
      <type>Main</type>
      <value>\d*</value>
      <webElementGuid>4fc4f576-aba6-46b0-bad6-338e30b7f816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputCelularConsignadoComp</value>
      <webElementGuid>eeb298ae-8430-44f2-81d2-f083dd55487b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputCelularConsignadoComp&quot;)</value>
      <webElementGuid>ccca85bb-2305-4a0a-9fb3-d0011966445b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputCelularConsignadoComp']</value>
      <webElementGuid>a602b3c2-f824-489f-8bc5-e637ead809dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-quien-recibe/div/div[2]/div[3]/div/input</value>
      <webElementGuid>090db60c-1940-4f8a-859f-44a60fb94ffd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/input</value>
      <webElementGuid>6ec8c7b9-f0b0-4421-91bb-a07abb9cf04b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputCelularConsignadoComp']</value>
      <webElementGuid>001cc6a8-e35f-4a6f-8c5b-e1616782c666</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
