<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NOMBRES(S)_inputApePatConsignado</name>
   <tag></tag>
   <elementGuidId>2f1665e5-69f7-45ac-8633-42dca051f90e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputApePatConsignado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputApePatConsignado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b0221044-e0fa-42e3-a837-c1b3750c6c53</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>79da6695-546b-4016-87cd-e0a68499777c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>267d60c8-eed3-4b0b-b3fa-8bba7aa59c10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputApePatConsignado</value>
      <webElementGuid>eeed9084-577b-478b-8a8a-06e6f2fae9ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputApePatConsignado</value>
      <webElementGuid>7db68993-95e9-47d1-aaf9-346d91971345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-pristine ng-touched</value>
      <webElementGuid>1e20d12a-00c9-4ce3-894c-f0ffb062a415</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>52a14400-a42f-4cce-b324-49ff74ae39e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputApePatConsignado</value>
      <webElementGuid>f74f3853-3d03-4708-84b4-a9efd0d671d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputApePatConsignado&quot;)</value>
      <webElementGuid>d38f6c79-00da-47e9-be90-f80d78987218</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputApePatConsignado']</value>
      <webElementGuid>98478ef6-1fae-45b8-bc96-b19387596ba0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[4]/div[2]/div/input</value>
      <webElementGuid>4ad599fb-58d3-4c75-9761-c6ece47e7d5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/input</value>
      <webElementGuid>126814ff-8d7b-46c3-9e4f-ab9a2c662819</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputApePatConsignado']</value>
      <webElementGuid>1a589f95-5f56-40d9-846d-3e1381b3145d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
