<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NMERO DOCUMENTO_inputNombreCompletoCo_df80e8</name>
   <tag></tag>
   <elementGuidId>d2dfc9bf-0d93-454f-9305-f3daa97ad51e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputNombreCompletoConsignado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputNombreCompletoConsignado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>465bfa6f-2aeb-4c44-95ed-9d7d5ded391a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ef37da3e-d3f6-4e7d-83c4-57a6c66d16b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>df91df42-aed3-45d4-bcf1-8e3cf0810907</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputNombreCompletoConsignado</value>
      <webElementGuid>17627799-5b0f-4bca-ae46-847b1b169621</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputNombreCompletoConsignado</value>
      <webElementGuid>6a158ece-b45c-49ac-9b35-13bec595fa88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>d36d830f-83a4-48ea-b194-578e0434f8ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>6532ea7d-9073-482a-9ddf-217b0d0899b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputNombreCompletoConsignado</value>
      <webElementGuid>adcde143-4cac-4ecd-a212-316dbf4cd19b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputNombreCompletoConsignado&quot;)</value>
      <webElementGuid>51044a4c-810a-4afb-b58b-75bf89d443ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputNombreCompletoConsignado']</value>
      <webElementGuid>c1336173-ccae-479c-bb29-ee43d08fd2ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[4]/div/input</value>
      <webElementGuid>2d5c423c-9347-4acc-817d-d56870e4a3e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>27279317-7f35-40a0-a23a-eac5af8a05c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputNombreCompletoConsignado']</value>
      <webElementGuid>a76dcc73-dbe8-4b08-b830-1033bd66e646</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
