<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TIPO DE DOCUMENTO  DNI  RUC  C.E_1</name>
   <tag></tag>
   <elementGuidId>26db2770-709e-4748-87c4-c00398e9d6a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tipoDocumentoConsignadoComp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoDocumentoConsignadoComp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4391d1a3-6975-4cb9-a748-1c167a9bba60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoDocumentoConsignadoComp</value>
      <webElementGuid>3382d329-ebc2-45ee-b8c3-0395b4404fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>tipoDocumentoConsignadoComp</value>
      <webElementGuid>d52571a3-e7ff-448e-b562-1f1f5b21a666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>tipoDocumentoConsignadoComp</value>
      <webElementGuid>4b6c2b73-cdd6-43c9-bfd0-0f5048145d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1233b028-160e-44f2-9881-4314c44073b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d932e373-45ca-4623-9e1e-efb5d0a99edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> TIPO DE DOCUMENTO  DNI  RUC  C.E. </value>
      <webElementGuid>2c7d96ba-75eb-45ef-90b7-26c80a2c2c36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoDocumentoConsignadoComp&quot;)</value>
      <webElementGuid>e17099c0-3f74-40e6-ad3f-5696e0299433</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoDocumentoConsignadoComp']</value>
      <webElementGuid>2c43199e-9730-40fa-8fef-7c321e9ebead</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-quien-recibe/div/div[2]/div/select</value>
      <webElementGuid>80658bef-1705-4841-9965-8581117a76e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completa los datos de la persona que recibirá tu envío.'])[1]/following::select[1]</value>
      <webElementGuid>23565c02-9889-4476-9c67-54b8b060af61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo de entrega'])[1]/following::select[1]</value>
      <webElementGuid>309e32b9-8047-4c48-a473-d70e6e4d679e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NÚMERO DOCUMENTO'])[1]/preceding::select[1]</value>
      <webElementGuid>35b54bdc-2d46-4890-9ade-d12f70033d8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CELULAR'])[1]/preceding::select[1]</value>
      <webElementGuid>07ce5cdb-6e1b-4208-8259-3d8905686b34</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e9ca423d-136e-4aad-af3d-3c3ed5e2af37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoDocumentoConsignadoComp' and (text() = ' TIPO DE DOCUMENTO  DNI  RUC  C.E. ' or . = ' TIPO DE DOCUMENTO  DNI  RUC  C.E. ')]</value>
      <webElementGuid>c86e1d14-e701-4c34-9ff9-54ba6608d166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona un tipo de documento.'])[1]/preceding::select[1]</value>
      <webElementGuid>9960892b-27a8-4acc-9b17-80b38dce846e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
