<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FOLIOS  1 FOLIO  2 FOLIOS  3 FOLIOS</name>
   <tag></tag>
   <elementGuidId>6dee91e7-7e8d-4dea-85d8-58520e417656</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cantidadFolios</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cantidadFolios']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>84d40a07-25f4-4454-b99b-a76128add322</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cantidadFolios</value>
      <webElementGuid>c18bf229-6de0-42e2-bf4c-a4a2047bfec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cantidadFolios</value>
      <webElementGuid>d846d4a4-7ced-4e4f-80c9-16021ce04f46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>cantidadFolios</value>
      <webElementGuid>1a00206d-fbf4-448a-a1ac-8fd70ac157fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b8ed466-6891-48a5-a5c1-6a7462fa49f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3b09fd9d-b2fb-4989-8708-aa5b606e8e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FOLIOS  1 FOLIO  2 FOLIOS  3 FOLIOS </value>
      <webElementGuid>6f3dc143-0547-4398-a64d-f777b7cb3f2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cantidadFolios&quot;)</value>
      <webElementGuid>c2597245-2e4a-49c4-a4ee-5bb9cacb77af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cantidadFolios']</value>
      <webElementGuid>9cd6dd52-46ab-4511-a335-a0a1b828a4dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[2]/select</value>
      <webElementGuid>8867d094-e38e-4bf5-818a-c4c33d00fb7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad de Folios:'])[1]/following::select[1]</value>
      <webElementGuid>fdfe940c-e794-4ac3-a741-d49d63a36bf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retorno de Cargo'])[1]/following::select[1]</value>
      <webElementGuid>7919cb3d-7718-48b0-8130-b552315f59d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿A dónde retornamos el cargo?'])[1]/preceding::select[1]</value>
      <webElementGuid>1d588ce6-75b6-414a-8ba2-86d0d7b178e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>7b9bde65-00ec-4584-b992-c6b642630da9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cantidadFolios' and @id = 'cantidadFolios' and (text() = ' FOLIOS  1 FOLIO  2 FOLIOS  3 FOLIOS ' or . = ' FOLIOS  1 FOLIO  2 FOLIOS  3 FOLIOS ')]</value>
      <webElementGuid>d5d12cb3-c13c-4078-829c-e4fd9c39690d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione una cantidad de Folios.'])[1]/preceding::select[1]</value>
      <webElementGuid>0342a7da-3a49-4525-ab2a-f444a220f52f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
