<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECCIONE TIENDA LINCE - AV GENERAL_0efa9b</name>
   <tag></tag>
   <elementGuidId>f9f06d58-f160-4b4c-87f0-b4e25506753d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectOficinasRetornoCargo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOficinasRetornoCargo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5f6a4a1b-3b3c-484b-832f-c9ca855761f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>d50752cd-84ba-4349-abf2-ef0001bbb8c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>eb5d80de-98f9-4282-a2e5-07803ef2adfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>5b59d556-e777-458e-8c49-bb76d7e15f4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>f6aa3144-226b-4456-b7c6-f81622635843</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECCIONE TIENDA LINCE - AV GENERAL ALVAREZ DE ARENALES NRO 1775  </value>
      <webElementGuid>460f15fa-617e-40d3-bc09-87fec7b8192b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOficinasRetornoCargo&quot;)</value>
      <webElementGuid>daab0017-6afa-4cb7-9cbc-73d4f33f7239</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOficinasRetornoCargo']</value>
      <webElementGuid>95047a20-0a8c-417c-b1c9-e600cd29b3f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div/div[2]/select</value>
      <webElementGuid>ecbb14f2-9b5f-4f6d-82a9-4157d5e7d2a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESE EL DESTINO DEL CARGO'])[1]/following::select[1]</value>
      <webElementGuid>1834c0e1-2d20-48f9-8243-3e496347c4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops, consolas, etc'])[2]/following::select[1]</value>
      <webElementGuid>2d628e34-14dc-4b06-96bc-586dae7ecb90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[1]</value>
      <webElementGuid>04f00dc6-4600-4a0d-bf5c-047c5d581e10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::select[1]</value>
      <webElementGuid>0da31adf-edc7-4122-a8f8-3b32c3c10c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/select</value>
      <webElementGuid>afa80d66-c62c-4e3a-8732-658fa99fcb82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOficinasRetornoCargo' and (text() = 'SELECCIONE TIENDA LINCE - AV GENERAL ALVAREZ DE ARENALES NRO 1775  ' or . = 'SELECCIONE TIENDA LINCE - AV GENERAL ALVAREZ DE ARENALES NRO 1775  ')]</value>
      <webElementGuid>354bb8bc-e2d3-4e90-855a-34a321705a67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
