<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECCIONE TIENDA ATE - AV JAVIER PR_1a42df</name>
   <tag></tag>
   <elementGuidId>bfc64c7a-5991-4acd-b178-6af80237132e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectOficinasRetornoCargo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOficinasRetornoCargo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>60bb4226-114e-428c-badb-a7715c390bfb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>ebca622e-1517-4cf6-9680-10140b6b6393</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>3fa2d50a-d2b6-4fd7-b1c8-8594dbd0f17a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>0a0164d5-a828-48c3-bd0d-72ff6cfb8af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>2393be0f-9969-444c-b9b9-ff5455bfc3b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECCIONE TIENDA ATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO   ATE - AV CARRETERA CENTRAL 7.5 KM S/N   ATE - CA 1 DE MAYO MZ 11 LTE 10 URB SAN GREGORIO   ATE - AV LA ESTRELLA S/N URB SANTA CLARA ((CENTRO COMERCIAL REAL PLAZA ) AL FRENTE DE TAI LOY)  ATE - AV LOS QUECHUAS S/N URBANIZACION SALAMANCA   ATE - Avenida Nicolás Ayllón, Ate, Perú(AV. CARRETERA CENTRAL 14.8 KM. GLORIA GRANDE LIMA - LIMA - ATE)  ATE - AV LOS QUECHUAS NRO 1485 URB SALAMANCA  </value>
      <webElementGuid>e5ca46c7-ff6a-475d-ac3c-968731998f8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOficinasRetornoCargo&quot;)</value>
      <webElementGuid>e57d52c0-5e2f-4104-a59e-44217b3e9587</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOficinasRetornoCargo']</value>
      <webElementGuid>3a056b11-0a94-463c-bd1c-e1af4e61e8c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div/div[2]/select</value>
      <webElementGuid>63019511-88a0-4ce8-9e5d-9527d1de1f74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESE EL DESTINO DEL CARGO'])[1]/following::select[1]</value>
      <webElementGuid>2c9d6c60-cef5-4191-8a47-68404fe8015c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops, consolas, etc'])[2]/following::select[1]</value>
      <webElementGuid>ff2657b3-998e-458f-b14e-12763b085777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[1]</value>
      <webElementGuid>4f3de0e3-deb5-47a0-89a1-f6b7bff8fe2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::select[1]</value>
      <webElementGuid>c7df57b8-27ba-4498-b247-8464d2cd70cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/select</value>
      <webElementGuid>7e387cd1-fb3b-48f2-a82f-f3435a66994a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOficinasRetornoCargo' and (text() = 'SELECCIONE TIENDA ATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO   ATE - AV CARRETERA CENTRAL 7.5 KM S/N   ATE - CA 1 DE MAYO MZ 11 LTE 10 URB SAN GREGORIO   ATE - AV LA ESTRELLA S/N URB SANTA CLARA ((CENTRO COMERCIAL REAL PLAZA ) AL FRENTE DE TAI LOY)  ATE - AV LOS QUECHUAS S/N URBANIZACION SALAMANCA   ATE - Avenida Nicolás Ayllón, Ate, Perú(AV. CARRETERA CENTRAL 14.8 KM. GLORIA GRANDE LIMA - LIMA - ATE)  ATE - AV LOS QUECHUAS NRO 1485 URB SALAMANCA  ' or . = 'SELECCIONE TIENDA ATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO   ATE - AV CARRETERA CENTRAL 7.5 KM S/N   ATE - CA 1 DE MAYO MZ 11 LTE 10 URB SAN GREGORIO   ATE - AV LA ESTRELLA S/N URB SANTA CLARA ((CENTRO COMERCIAL REAL PLAZA ) AL FRENTE DE TAI LOY)  ATE - AV LOS QUECHUAS S/N URBANIZACION SALAMANCA   ATE - Avenida Nicolás Ayllón, Ate, Perú(AV. CARRETERA CENTRAL 14.8 KM. GLORIA GRANDE LIMA - LIMA - ATE)  ATE - AV LOS QUECHUAS NRO 1485 URB SALAMANCA  ')]</value>
      <webElementGuid>c44f4928-9b48-4fd9-b347-bd3683852264</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-que-envias/app-cargo-adjunto/div/div/div[5]/div/div[2]/select</value>
      <webElementGuid>ca18e88b-c473-473f-8883-a78cc8122620</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
