<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Aceptar</name>
   <tag></tag>
   <elementGuidId>b504c721-c39f-43ef-b508-3123e4021479</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#aceptarCargoAdjunto</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//small[@id='aceptarCargoAdjunto']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>8b5e43b1-c48d-42b2-a87d-b79cedf1048c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span-accept aceptar-button</value>
      <webElementGuid>8b77ea05-4e21-4ed5-88d5-bf7d874826ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>2c6621c2-0c11-46ea-998c-572299f32be8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aceptarCargoAdjunto&quot;)</value>
      <webElementGuid>378de91a-4518-4ea8-9229-cd54167d9133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aceptarCargoAdjunto</value>
      <webElementGuid>4022380e-3956-4aa8-8aed-27d7e0b82a23</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='aceptarCargoAdjunto']</value>
      <webElementGuid>884d9b27-5525-4f1d-973e-bd023df17b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-que-envias/app-cargo-adjunto/div/div/div[5]/div[2]/small[2]</value>
      <webElementGuid>ccf859ed-a551-4383-a402-785612818ea1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::small[1]</value>
      <webElementGuid>a91db60b-2e81-4a77-874d-06d4a4c03663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESE EL DESTINO DEL CARGO'])[1]/following::small[2]</value>
      <webElementGuid>ddc67ea2-b893-4fbf-a5af-edd1bdd4cee2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[2]/preceding::small[1]</value>
      <webElementGuid>9ef7a325-06f6-470c-b46f-3c4569318509</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[3]/preceding::small[1]</value>
      <webElementGuid>0d649f86-66f2-4146-a717-0ff4042c47ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceptar']/parent::*</value>
      <webElementGuid>2f1d2d12-dd66-43f4-a6fa-daadfa7c9df1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/small[2]</value>
      <webElementGuid>2e3c4c85-9111-45ea-8b9e-fc91b2a412f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'aceptarCargoAdjunto' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>b5ea56a0-bfef-45d3-95cf-686f386bd833</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aceptarValidacionApellido']/small</value>
      <webElementGuid>fcfbe348-0995-48b7-8ab5-8c2eddab9599</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APELLIDO PATERNO'])[1]/following::small[2]</value>
      <webElementGuid>16e509ef-af68-4dc0-a83a-b8f718d9ed62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-validacion-apellido-modal/div/div/div[3]/div[2]/small</value>
      <webElementGuid>50f5016f-54da-45fe-abbe-ab6a71206c68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>fb1ee33d-32c4-4ba7-9ced-e8ae2302b7d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div[2]/small[2]</value>
      <webElementGuid>0d797434-00e0-44db-9edb-576aab6c5079</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'aceptarCargoAdjunto', '&quot;', ')')])[1]/preceding::small[1]</value>
      <webElementGuid>2e5a4c19-d43a-43c8-a2c0-02201b245f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aceptarValorado']/small</value>
      <webElementGuid>18522a21-e646-4456-9366-4247c73e1912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar envío'])[1]/following::small[1]</value>
      <webElementGuid>56c39e7d-81c1-4f8c-86e6-aaaa9397fdd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recojo en tienda no disponible'])[1]/following::small[3]</value>
      <webElementGuid>7f8edd90-a1ef-4c1c-852a-1fcbe52dce31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'aceptarValorado', '&quot;', ')/small[@class=', '&quot;', 'span-accept', '&quot;', ']')])[1]/preceding::small[1]</value>
      <webElementGuid>305d8d2c-cef1-4606-93da-70a7a6a7a188</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-alerta-valorado/div/div/div[2]/div[2]/small</value>
      <webElementGuid>80783221-aa1f-43c9-a7ad-25288ffcd313</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIA'])[1]/following::small[2]</value>
      <webElementGuid>ba0343a4-458b-4a50-8bdd-d7fe71674457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div/small[2]</value>
      <webElementGuid>e9576001-d9b5-46b5-b489-47136e4ee680</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops, consolas, etc'])[2]/following::small[2]</value>
      <webElementGuid>63c2f6dc-52b1-4b58-9a1f-eaca7306cf1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/small[2]</value>
      <webElementGuid>8754f195-c891-4815-a0c4-3ce848d62a14</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
