<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_INGRESE DESTINO</name>
   <tag></tag>
   <elementGuidId>dbd23616-014c-4ac1-bda9-965454111128</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>small.font-18-destino</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='seleccionaDestino']/div/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>2e28ef48-c132-4cfd-9847-1e8befd2c1cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>8a73dc96-ceed-4669-849d-b16095d78a81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-18-destino</value>
      <webElementGuid>9f578dab-de73-4037-9609-3420ad3db9f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>INGRESE DESTINO</value>
      <webElementGuid>c07ab3ba-c131-4ed2-bc2f-50e8d162ae2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seleccionaDestino&quot;)/div[@class=&quot;position-a&quot;]/small[@class=&quot;font-18-destino&quot;]</value>
      <webElementGuid>c9d5d1a1-c929-4111-afa3-bdba04bed0d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='seleccionaDestino']/div/small</value>
      <webElementGuid>b7f0c384-b9a7-46f4-83b9-c03d6db98a72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hacia:'])[1]/following::small[1]</value>
      <webElementGuid>cf60569c-1299-4da2-8441-c7733708f68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORIGEN'])[2]/following::small[2]</value>
      <webElementGuid>b4f70abb-0947-4705-9632-36e7fc330425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DESTINO'])[2]/preceding::small[1]</value>
      <webElementGuid>bfde564b-faac-4fc2-9959-b4c2f2a6ab4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione el Destino.'])[1]/preceding::small[2]</value>
      <webElementGuid>061daa0b-2290-45b0-8d44-28b9092e845f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='INGRESE DESTINO']/parent::*</value>
      <webElementGuid>4564fd37-6441-4422-9c74-0518bda376c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/small</value>
      <webElementGuid>ad0ed135-6870-4ac8-9c1e-3014a20ae33b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'INGRESE DESTINO' or . = 'INGRESE DESTINO')]</value>
      <webElementGuid>fbf673bb-44d0-4041-80e1-e261a819d841</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
