<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Cancelar</name>
   <tag></tag>
   <elementGuidId>50344947-1de2-4fe3-b99a-be6cf11afd69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>small.span-cancel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cancelarValidacionApellido']/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>7aa452df-1670-498e-8300-e3e528894750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelarCargoAdjunto</value>
      <webElementGuid>3b9f0c07-b5b6-41c2-9b23-a91a3e078afe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span-cancel</value>
      <webElementGuid>369e8800-ed30-4fc6-b26e-8a4fb55ed1dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>9e863375-b941-4d7d-a3b2-134fc09c65f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelarValidacionApellido&quot;)/small[@class=&quot;span-cancel&quot;]</value>
      <webElementGuid>29759bf1-b5a2-446a-a188-5b07c9870f6d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cancelarValidacionApellido']/small</value>
      <webElementGuid>1b8ce18e-bd47-4130-ab4d-f7311374f094</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APELLIDO PATERNO'])[1]/following::small[1]</value>
      <webElementGuid>635369cf-c6f8-4640-a945-5af303e1cb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escriba su primer apellido igual al del documento de identidad'])[1]/following::small[1]</value>
      <webElementGuid>6a6bf5d7-7b3d-4792-8da9-ce6e36e0b6f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::small[1]</value>
      <webElementGuid>8b8c2c30-d7f2-4c3c-8b28-611b332cc1be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancelar']/parent::*</value>
      <webElementGuid>ad57eeb9-cfb7-4753-aa1b-69d6a5b39691</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-validacion-apellido-modal/div/div/div[3]/div/small</value>
      <webElementGuid>552d0732-ba03-42e4-a6bd-ee1bccd67e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Cancelar' or . = 'Cancelar')]</value>
      <webElementGuid>8a0dd6c8-a819-4219-9f57-fe0e81a8c1d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='cancelarCargoAdjunto']</value>
      <webElementGuid>659e45f2-6510-4583-a97d-6a48d592754e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-que-envias/app-cargo-adjunto/div/div/div[5]/div[2]/small</value>
      <webElementGuid>2e64d5ec-261f-4a8b-a268-5b9b5e07b54e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIA'])[1]/following::small[1]</value>
      <webElementGuid>c6950e46-861a-4150-bdc2-8926973ff822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIRECCIÓN EXACTA'])[1]/following::small[1]</value>
      <webElementGuid>41bb108e-3496-47f3-9e8a-c2c5428078e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[2]/preceding::small[2]</value>
      <webElementGuid>5e8d3f71-da47-42ef-926d-bb521b535c2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/small</value>
      <webElementGuid>8029a04b-b187-4fe1-954d-c8dcc82ff27c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'cancelarCargoAdjunto' and (text() = 'Cancelar' or . = 'Cancelar')]</value>
      <webElementGuid>b69b431a-5421-4d2b-8de6-c52fd57b41d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div[2]/small</value>
      <webElementGuid>71111611-358d-419c-b35c-c4473e523bc2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Este campo es obligatorio.'])[1]/following::small[1]</value>
      <webElementGuid>88740806-a6ee-4750-835f-fbe3d02d501e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'cancelarCargoAdjunto', '&quot;', ')')])[1]/preceding::small[2]</value>
      <webElementGuid>ed6a699f-f06a-4342-92d8-682a9abcdb8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
