<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUAR_1</name>
   <tag></tag>
   <elementGuidId>39a08187-075c-43f7-b900-c949201944fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#avanzarQueEnvias</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='avanzarQueEnvias']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;CONTINUAR&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a90b940f-907c-431e-ba49-cf81b7e9054b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>avanzarQueEnvias</value>
      <webElementGuid>c8e9d159-0a08-4a86-b1dc-4cf9b34178fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 custom-btn boton</value>
      <webElementGuid>92b11209-b3bb-4e92-b946-703a84a195a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>2fa1818f-2da7-4e3d-bd4f-ad86d5d794c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>5d43d7c1-c144-478e-86fa-ef689acde250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>c9414f8d-a13a-47ef-9075-ec0e2fa7320b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avanzarQueEnvias&quot;)</value>
      <webElementGuid>a611b66c-c7b3-4105-9e51-b59417946ba1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='avanzarQueEnvias']</value>
      <webElementGuid>81b9e2fa-671f-47ca-8a2c-a1007dc8396e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[8]/button[2]</value>
      <webElementGuid>a7ebb3b7-d3f3-4d60-abe3-1622805f2f31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[2]/following::button[1]</value>
      <webElementGuid>3e937c5e-a12e-49e5-8166-dc63b5514cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='términos de uso y politica de privacidad'])[1]/following::button[2]</value>
      <webElementGuid>7e62e047-62fe-4278-9737-8e5f97d74ab2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[8]/button[2]</value>
      <webElementGuid>2d5ee0df-71e9-43ef-b549-6f161d5030c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'avanzarQueEnvias' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>c3cbe574-8b2c-4162-bb89-60df080dfcc1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
