<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TIPO DE DOCUMENTO  DNI  RUC  C.E</name>
   <tag></tag>
   <elementGuidId>200dd246-1e3b-4510-887e-0c3bdb8a91fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tipoDocumentoConsignado</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoDocumentoConsignado']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#tipoDocumentoConsignado</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ea4d1e25-3fdd-4f8c-bf66-faa7e4e4a960</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoDocumentoConsignado</value>
      <webElementGuid>ac2aa3b4-d2c5-42fd-a49b-4785719a1fe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>tipoDocumentoConsignado</value>
      <webElementGuid>46fabf34-e8c2-4451-aeb6-bd3b49ab5875</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>tipoDocumentoConsignado</value>
      <webElementGuid>428a31fa-011f-4b7f-b5ff-9e78d4778c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>85c8772d-0ec1-4b87-b902-e2c5a060d3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cec0cc41-5164-423b-908e-7382f2bc4197</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> TIPO DE DOCUMENTO  DNI  RUC  C.E. </value>
      <webElementGuid>d4c28906-8897-4bef-b856-03a98f6f5653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoDocumentoConsignado&quot;)</value>
      <webElementGuid>630bee8b-be0f-4706-a823-627981488775</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoDocumentoConsignado']</value>
      <webElementGuid>87c17eda-5bcb-4f1b-9bb2-198889426944</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[3]/div/select</value>
      <webElementGuid>6fb33e02-5fbd-48d5-9b8c-90666178ef94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completa los datos de la persona que recibirá tu envío.'])[1]/following::select[1]</value>
      <webElementGuid>8b9f9afa-a2dd-4ad5-a7b3-4db089ce0ccf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Datos de quién recibe'])[1]/following::select[1]</value>
      <webElementGuid>a9681d64-2cd4-4f93-af50-e49eb96fc046</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NÚMERO DOCUMENTO'])[1]/preceding::select[1]</value>
      <webElementGuid>e6a6a3ed-4e9f-46bf-808f-7ce49b686fe7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOMBRES(S)'])[1]/preceding::select[1]</value>
      <webElementGuid>48434068-c0d1-4c02-a3b6-0ac67bec4674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>a63f0bd6-674c-4d25-a0dc-6955d5fd9138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoDocumentoConsignado' and (text() = ' TIPO DE DOCUMENTO  DNI  RUC  C.E. ' or . = ' TIPO DE DOCUMENTO  DNI  RUC  C.E. ')]</value>
      <webElementGuid>2ced3b68-8d66-403d-85fa-db40467b5326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
