<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No s el peso de mi envo</name>
   <tag></tag>
   <elementGuidId>652f04ce-cb57-4db1-80ef-8c0b671d625d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonIngresarMedidas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonIngresarMedidas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6651d2b5-da74-435d-b539-0b8a7bf7bc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonIngresarMedidas</value>
      <webElementGuid>b5d4db7f-29bf-4043-99ca-b0d3a3f5b269</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton-dimensiones font-11 x-3 button-dimension size-button-dimension-responsive button-position-responsive</value>
      <webElementGuid>47252fd0-f83a-4a77-beef-28a78ad47481</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1d3d3926-0f4e-4a29-a99b-998014102800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No sé el peso de mi envío</value>
      <webElementGuid>1db9066c-e0f7-419d-a766-fe4926c03bcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonIngresarMedidas&quot;)</value>
      <webElementGuid>fae78074-ce7a-4863-a951-fa48ab5d318f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonIngresarMedidas']</value>
      <webElementGuid>edc3defe-2023-4e09-925b-00cf961cde45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[4]/button</value>
      <webElementGuid>fa05f966-4f00-4289-b27d-2ed165d82952</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='consolas, etc'])[1]/following::button[1]</value>
      <webElementGuid>1ca9b2e2-dba5-43c4-bab9-f76ddff258b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops,'])[1]/following::button[1]</value>
      <webElementGuid>19fab112-e506-4915-8238-98bfe3a732b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quiero retorno de cargo'])[1]/preceding::button[1]</value>
      <webElementGuid>de3ecf0d-b2e6-4bd7-978a-08305eefffb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>32601a9b-c232-42e8-b79b-e77c23828506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonIngresarMedidas' and (text() = 'No sé el peso de mi envío' or . = 'No sé el peso de mi envío')]</value>
      <webElementGuid>8ed7c587-6196-414f-88dc-b8c64a6efe01</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
