<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_VOLVER</name>
   <tag></tag>
   <elementGuidId>750a49a2-3235-4a63-b415-09f66746bee4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='volverDestinoEnvio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#volverDestinoEnvio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eceb012e-0c78-414a-bb3e-4fab263e16f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>volverDestinoEnvio</value>
      <webElementGuid>d7443284-94ad-4e20-9cb6-9e03fd337233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondary-boton px-3 me-2</value>
      <webElementGuid>8c12d7e9-b3e0-4ac4-8e43-5d05f39a48f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VOLVER</value>
      <webElementGuid>bfff71e6-4658-484c-b027-64c601948ba9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;volverDestinoEnvio&quot;)</value>
      <webElementGuid>5a4f7ee2-caa7-4128-b132-3e869c38aefd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='volverDestinoEnvio']</value>
      <webElementGuid>b1d48b10-5c36-47b0-8b17-723c7d3da2f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[4]/button</value>
      <webElementGuid>e852d31c-6ead-473d-84b4-afd7a639ff79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S/ 30.90'])[2]/following::button[1]</value>
      <webElementGuid>c6aa4d48-ffe9-45ee-b53b-4e59a04e32bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Total:'])[1]/following::button[1]</value>
      <webElementGuid>f3e51c41-64ed-40b0-be57-c9e36bb67bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='IR A PAGAR'])[1]/preceding::button[1]</value>
      <webElementGuid>81a88533-2452-4bb4-9966-9f735c9cb3c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'volverDestinoEnvio', '&quot;', ')')])[1]/preceding::button[2]</value>
      <webElementGuid>718df2b7-7253-49c0-847d-03b9a3f7adcc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VOLVER']/parent::*</value>
      <webElementGuid>1a4f7b8a-5901-4d41-8bd1-75d277474803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>46584f87-b6df-4d14-9315-72a7780919b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'volverDestinoEnvio' and (text() = 'VOLVER' or . = 'VOLVER')]</value>
      <webElementGuid>a4340965-4c31-463e-881a-f9f6170b6c00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
