<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_CONTINUAR_btn-icon</name>
   <tag></tag>
   <elementGuidId>98708611-d5f4-427a-b1e6-aae9bbea94b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#avanzarQueEnvias > img.btn-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='avanzarQueEnvias']/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>784ef5f8-a256-4f12-9bcd-6c3550be27aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icon_arrow_right.png</value>
      <webElementGuid>dc13ffcb-bbde-41a3-b387-c3f2e9f36c14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>6263a9a1-3674-4159-909c-86ce153287b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>dd7f40df-4173-40f4-8953-f98afcba91d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon</value>
      <webElementGuid>d48008fb-df29-481b-b09f-8e11aa87aa33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avanzarQueEnvias&quot;)/img[@class=&quot;btn-icon&quot;]</value>
      <webElementGuid>927e3e47-4329-4fbd-b71c-6c93b29f03d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='avanzarQueEnvias']/img</value>
      <webElementGuid>5c57c3a7-34e8-449d-b4d2-e9acd873326a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[8]/button[2]/img</value>
      <webElementGuid>86a83351-75c9-4b3e-b663-90d475a71803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/icon_arrow_right.png']</value>
      <webElementGuid>5b7191d6-3109-4b82-9eda-bf7ffed5b0de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='avanzarToSelectOrigen']/img</value>
      <webElementGuid>372deb95-b10e-404a-8a90-21b9385e5dfb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/img</value>
      <webElementGuid>aae6edfb-49ca-4323-945e-4489ef08c053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='guardarCliente']/img</value>
      <webElementGuid>c3cec7f7-a8af-4b35-a0c1-3d0425d1225e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='avanzarListarEnvios']/img</value>
      <webElementGuid>53daacb7-fbd9-4cb3-871c-dc9628b86185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button[2]/img</value>
      <webElementGuid>c25dd870-1c6d-4075-b8db-209aac7f6b65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='avanzarQuienRecibe']/img</value>
      <webElementGuid>f2d3b1cb-937a-4ac3-9206-0474253a2007</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[7]/button[2]/img</value>
      <webElementGuid>1c72be6e-7971-4fff-aa33-47ff79b47632</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='avanzarTipoArticulo']/img</value>
      <webElementGuid>585d109c-509f-4d87-ba82-82aee87c5598</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/icon_arrow_right_grey.png']</value>
      <webElementGuid>030a5b60-e1f2-491f-942c-62442487f84a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
