<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TIPO DE ARTCULO  ACCESORIOS Y EQUIPO_f94c1d</name>
   <tag></tag>
   <elementGuidId>1118fac4-8317-494b-80c3-ce6315b622e1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoArticulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipoArticulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>94a089b7-4bd5-4872-9a40-c7d2e934a590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoArticulo</value>
      <webElementGuid>f376fc2e-fb16-4d76-831e-ede2d6dc9998</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>tipoArticulo</value>
      <webElementGuid>aadddd3d-5a24-4535-a7e1-b36cf0c53010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-size ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3c24840c-4003-4bfd-ab0a-2499237d6b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>tipoArticulo</value>
      <webElementGuid>2678d121-97ab-4c85-8d07-f31c5e4aa427</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3c1982d5-1d80-436e-8d50-cb12df3cd098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f8640709-acd4-422a-b87d-5577ac6c42db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> TIPO DE ARTÍCULO  ACCESORIOS Y EQUIPOS ELECTRONICOS  ACCESORIOS PARA FIESTAS  ARTÍCULOS DE LIMPIEZA  ARTÍCULOS PUBLICITARIOS  BISUTERIA  CAJA  TARJETAS PERSONALES  MUEBLES Y DECOHOGAR  FERRETERÍA Y CONSTRUCCIÓN  ALIMENTACION Y BEBIDAS  COSMETICOS  ELECTROHOGAR  JUGUETES  MATERIAL MEDICO  MEDICINAS  REPUESTOS  ROPA Y ACCESORIOS  VALIJA-DOCUMENTOS  UTILES DE ESCRITORIO  UTILES DE OFICINA </value>
      <webElementGuid>d49367cc-e607-46ae-b83c-0290fa8799e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoArticulo&quot;)</value>
      <webElementGuid>a1ab0f32-3c4f-4f3b-8a65-0b53c8cfccc2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoArticulo']</value>
      <webElementGuid>680c539c-da10-4923-8739-3e6b50d0b04c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[5]/div/select</value>
      <webElementGuid>ccf41f02-52de-4b1a-9435-9bd96d80ee5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione un tipo de artículo'])[1]/following::select[1]</value>
      <webElementGuid>495ad8b9-0500-4d91-89e5-0d5b3aa5a7fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOBRE'])[1]/following::select[1]</value>
      <webElementGuid>d606fbcb-f480-45a9-affa-3502f1b7dc46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALOR DEL CONTENIDO'])[1]/preceding::select[1]</value>
      <webElementGuid>d9cf2faa-5b99-40b7-ae51-d29d3bbbb888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESPECIFICAR ARTÍCULO'])[1]/preceding::select[1]</value>
      <webElementGuid>b3dcd56d-b5c7-4692-8527-67ca8af3d8d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>82bcf9a0-aec8-4b60-8ce7-fbd0d7986c51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoArticulo' and (text() = ' TIPO DE ARTÍCULO  ACCESORIOS Y EQUIPOS ELECTRONICOS  ACCESORIOS PARA FIESTAS  ARTÍCULOS DE LIMPIEZA  ARTÍCULOS PUBLICITARIOS  BISUTERIA  CAJA  TARJETAS PERSONALES  MUEBLES Y DECOHOGAR  FERRETERÍA Y CONSTRUCCIÓN  ALIMENTACION Y BEBIDAS  COSMETICOS  ELECTROHOGAR  JUGUETES  MATERIAL MEDICO  MEDICINAS  REPUESTOS  ROPA Y ACCESORIOS  VALIJA-DOCUMENTOS  UTILES DE ESCRITORIO  UTILES DE OFICINA ' or . = ' TIPO DE ARTÍCULO  ACCESORIOS Y EQUIPOS ELECTRONICOS  ACCESORIOS PARA FIESTAS  ARTÍCULOS DE LIMPIEZA  ARTÍCULOS PUBLICITARIOS  BISUTERIA  CAJA  TARJETAS PERSONALES  MUEBLES Y DECOHOGAR  FERRETERÍA Y CONSTRUCCIÓN  ALIMENTACION Y BEBIDAS  COSMETICOS  ELECTROHOGAR  JUGUETES  MATERIAL MEDICO  MEDICINAS  REPUESTOS  ROPA Y ACCESORIOS  VALIJA-DOCUMENTOS  UTILES DE ESCRITORIO  UTILES DE OFICINA ')]</value>
      <webElementGuid>3edf8bb7-cc33-4fba-9073-0945642a04bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
