<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LIMA - LIMA - SAN ISIDRO</name>
   <tag></tag>
   <elementGuidId>1a79f449-40b8-4a66-b8e5-939c78a543e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#opcion_150131</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opcion_150131']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>ff8b9bf1-0d1e-4d87-9414-9cf425826ba4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-origen hover</value>
      <webElementGuid>fe8bcb7e-9ff1-45df-ad0f-2ebe959575db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opcion_150131</value>
      <webElementGuid>341df6a8-84fe-4268-88e0-99b11658e9e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> LIMA - LIMA - SAN ISIDRO </value>
      <webElementGuid>aa1ebe01-9c0b-4670-8d7a-12a47540e65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opcion_150131&quot;)</value>
      <webElementGuid>2a4ecbf8-643b-46a9-bb7e-c0c79bd9ee5a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='opcion_150131']</value>
      <webElementGuid>81c1e9d7-7d42-4b53-af5d-9cf152f0f9c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autocompleteList']/div</value>
      <webElementGuid>c67b80e6-05fa-4885-ae56-17d406f06cb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESE EL DESTINO DEL CARGO'])[1]/following::div[2]</value>
      <webElementGuid>7fab14d1-2aa5-405f-bc77-16f3c9b4f36c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops, consolas, etc'])[2]/following::div[5]</value>
      <webElementGuid>0208a654-c6fa-442d-8948-1528ab323cfd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='DIRECCIÓN EXACTA'])[1]/preceding::div[1]</value>
      <webElementGuid>62e4efc8-c423-438a-8d28-1e4053851fbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIA'])[1]/preceding::div[2]</value>
      <webElementGuid>e9531323-cfa9-4269-a4d0-9256c4c2d7dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LIMA - LIMA - SAN ISIDRO']/parent::*</value>
      <webElementGuid>df6100ca-8f46-4b81-9e57-e8fd573bccb0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div</value>
      <webElementGuid>ae8b0163-1450-41aa-a41c-aa4b231d10a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'opcion_150131' and (text() = ' LIMA - LIMA - SAN ISIDRO ' or . = ' LIMA - LIMA - SAN ISIDRO ')]</value>
      <webElementGuid>0436ac0a-bafb-48fc-b026-8016dca73dce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
