<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUAR_1_2_3_4</name>
   <tag></tag>
   <elementGuidId>0edacd03-3aa5-4d3f-a52e-7fd70bc1d7f1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#avanzarSeccionDestino</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='avanzarSeccionDestino']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>92c16f9d-ceca-4279-9293-16837850d614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>avanzarSeccionDestino</value>
      <webElementGuid>3d951376-55a4-4105-82fa-564c4af510e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 custom-btn boton</value>
      <webElementGuid>a4d9033d-888f-4e2e-83e4-ecfeee811470</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>c9a856ed-d5b8-48e1-8177-53b24d9014fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>5bf06297-5d4b-4990-b12a-0a4073ba9b3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avanzarSeccionDestino&quot;)</value>
      <webElementGuid>3227314c-38ef-4c1b-9ec6-e4b58247fa79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>48ef6ddb-cf4f-4723-9c6f-aca4776113fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='avanzarSeccionDestino']</value>
      <webElementGuid>268ba4f2-caa1-4cc8-9b99-ff557b097a38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[6]/button[2]</value>
      <webElementGuid>95eeb905-1f33-4cc5-8394-3ad425d70f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[1]/following::button[1]</value>
      <webElementGuid>971e46db-c7d0-4918-9ef7-bb68a3b4f34e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CELULAR'])[1]/following::button[2]</value>
      <webElementGuid>07e40787-99ce-4084-9150-98dd8b58c52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tamaño del envío'])[1]/preceding::button[1]</value>
      <webElementGuid>abba795f-73e4-4fda-be72-e378f28eded4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>e927a0b3-4ed6-481c-98ae-4ae3ef54f8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'avanzarSeccionDestino' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>a565b0e1-fc60-459f-aa90-d97cfedbfcca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='avanzarQuienRecibe']</value>
      <webElementGuid>da2c6a1a-c391-4262-a865-b932d0e49cd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[7]/button[2]</value>
      <webElementGuid>6f86dfa2-36e1-425e-8694-0d6c229b36ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[2]/following::button[1]</value>
      <webElementGuid>637424f9-368f-4da1-8b5d-77e625190562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se aplica peso volumen en caso los paquetes tengan mayor tamaño que peso.'])[1]/following::button[2]</value>
      <webElementGuid>e2805512-63d7-4f67-933f-02df8bace558</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'avanzarQuienRecibe', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>76a08b43-5ac3-45f1-b651-7995a3260f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button[2]</value>
      <webElementGuid>4aa91d82-dbdc-420d-82ac-e3c5fa0e9fb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'avanzarQuienRecibe' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>8bbc3780-1894-4583-a1a2-d09942a0c003</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
