<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SOBRE</name>
   <tag></tag>
   <elementGuidId>258aece2-38a2-4f59-a17f-c0df8b749388</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonSobre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonSobre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e6f0d54-443e-4218-b0ab-df998b78e404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonSobre</value>
      <webElementGuid>d53836bc-f470-498f-b294-0455fb00af06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonComprobante ml-15</value>
      <webElementGuid>d8d59e24-dd15-4dcc-b849-c9355b0f3b56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f813234f-7e4b-4395-ab40-1169ba4c7974</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SOBRE</value>
      <webElementGuid>4aebebb5-e855-4058-8a96-49734c15dc56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonSobre&quot;)</value>
      <webElementGuid>de5cccf2-0f93-4bbf-be0a-a8813769fd29</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonSobre']</value>
      <webElementGuid>c6d16de3-6787-4510-8fc2-c0de39cd9f01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[3]/button[2]</value>
      <webElementGuid>8de94ecd-ddb5-4cff-8ad5-d0e93ddd1931</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAQUETE'])[1]/following::button[1]</value>
      <webElementGuid>8bbaca6d-e9c6-43a6-b42a-416721bf718e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona el tipo de envío que deseas realizar.'])[1]/following::button[2]</value>
      <webElementGuid>aa36be6d-04e9-46dc-a8c3-ee5d0ed07b1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione un tipo de artículo'])[1]/preceding::button[1]</value>
      <webElementGuid>62e3d173-9494-4481-a81b-5ff581f92339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALOR DEL CONTENIDO'])[1]/preceding::button[1]</value>
      <webElementGuid>9bf48778-67f4-4709-8d37-fe54f367ef03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SOBRE']/parent::*</value>
      <webElementGuid>4a408e40-0f80-4aa7-8bc8-9f318fb0ff04</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>43fa69eb-2e06-4a7d-a421-ee7c13e5cd23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonSobre' and (text() = 'SOBRE' or . = 'SOBRE')]</value>
      <webElementGuid>56dca1ee-dd14-4668-b8a7-8af5132c8f13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-que-envias/div/div/div/div/button[2]</value>
      <webElementGuid>2859b607-51fb-40ba-bfb3-c45d3787ca65</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione el tipo de envío que desea realizar.'])[1]/following::button[2]</value>
      <webElementGuid>b1da2da3-f9d2-4ea1-a6df-bed9a1863bab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESPECIFICAR ARTÍCULO'])[1]/preceding::button[1]</value>
      <webElementGuid>2e53c513-d360-4b99-90b2-d9c60891bf08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
