<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_No s el peso de mi envo</name>
   <tag></tag>
   <elementGuidId>bb78b8f9-c8ce-44ed-8541-4ec1a9580eca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonIngresarMedidas']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonIngresarMedidas</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d96cff69-3e39-46bc-89ba-ca51045f665b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonIngresarMedidas</value>
      <webElementGuid>7c0275f0-888a-40da-9ec3-86b748fa0937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton-dimensiones font-11 x-3 button-dimension size-button-dimension-responsive button-position-responsive ng-star-inserted</value>
      <webElementGuid>4237d250-e834-4a92-8451-51d6b8cfd66f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>d1a0d7f0-592a-449b-a537-6a1c0a9b09f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>No sé el peso de mi envío</value>
      <webElementGuid>5f445b2c-27f5-4817-823b-ef57e3833cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonIngresarMedidas&quot;)</value>
      <webElementGuid>76df05e8-5329-4ae7-88b7-2788bcbeaf57</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonIngresarMedidas']</value>
      <webElementGuid>21061623-7f0b-4cbf-a00d-e1069000e50b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[4]/button</value>
      <webElementGuid>7537018b-6c90-4b2d-9f80-d5c5865ed6eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='consolas, etc'])[1]/following::button[1]</value>
      <webElementGuid>f9060a85-5ace-44bc-aca1-d39c76573728</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops,'])[1]/following::button[1]</value>
      <webElementGuid>f1ca56f0-d1c1-4a54-aec0-2f4101cc246b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Quiero retorno de cargo'])[1]/preceding::button[1]</value>
      <webElementGuid>25e1a4e6-b9f7-4312-8fb9-0236446624f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>a5791125-9325-4fb1-8321-55e67802db6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonIngresarMedidas' and (text() = 'No sé el peso de mi envío' or . = 'No sé el peso de mi envío')]</value>
      <webElementGuid>dfbf461a-ad12-4cd5-a07f-73e91386c169</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
