<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CANCELAR</name>
   <tag></tag>
   <elementGuidId>b914cabe-2043-4d30-8bb5-2a870f0e5ff1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/main/app-listar-envios/app-modal-clave-seguridad/div/div/div/div/div[2]/div[5]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.cancelar-modal-clave</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9889b834-0cf5-458a-bf38-88e0e5526687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>cancelar-modal-clave</value>
      <webElementGuid>c06f1553-ffe7-4ef5-a4ea-738bbf7881d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CANCELAR</value>
      <webElementGuid>2becef14-57fd-4e7d-917c-75dee22424fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[1]/app-listar-envios[@class=&quot;ng-star-inserted&quot;]/app-modal-clave-seguridad[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;modal-overlay&quot;]/div[@class=&quot;modal-container&quot;]/div[@class=&quot;modal-body&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-8 col-sm-8 row d-flex justify-content-center&quot;]/div[@class=&quot;col-md-12 d-flex justify-content-center row mt-1&quot;]/button[@class=&quot;cancelar-modal-clave&quot;]</value>
      <webElementGuid>3def6122-8964-436c-9398-a5a03bdb1fbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/app-modal-clave-seguridad/div/div/div/div/div[2]/div[5]/button</value>
      <webElementGuid>5e57ef4c-5e0d-45da-b552-d2b51cba94b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ingrese una clave de 4 dígitos'])[1]/following::button[1]</value>
      <webElementGuid>04904e51-6c43-4278-bdcf-0c24e705ba97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Genera una clave y compártela con la persona que recogerá tu envío en tienda o agente.'])[1]/following::button[1]</value>
      <webElementGuid>9f9e6e29-af32-4bbb-bcd2-4acc3d5956da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[2]/preceding::button[1]</value>
      <webElementGuid>62f89f37-a0a7-4da5-99aa-157686ce23c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='CANCELAR']/parent::*</value>
      <webElementGuid>01392cc2-3620-4818-8ddc-6b6cb9ff2bac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/button</value>
      <webElementGuid>b1a2af48-daa7-440d-abe9-f4338ada1c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'CANCELAR' or . = 'CANCELAR')]</value>
      <webElementGuid>009bcbbb-fc14-4cd9-80af-d01bb0282311</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
