<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_VOLVER_1_2</name>
   <tag></tag>
   <elementGuidId>ce86e07a-e961-41cf-b604-b98e6f057fe3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='volverSeccionConsignado']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#volverSeccionConsignado</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>5b9a2c48-5551-4e24-8bbc-8527437d9a80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>volverSeccionConsignado</value>
      <webElementGuid>295bd69b-24cb-4160-b92d-f9e94b3074c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>secondary-boton px-3 me-2</value>
      <webElementGuid>f0e36bed-dd58-40fc-aed7-c7e03e7f873d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>VOLVER</value>
      <webElementGuid>20276262-0f1b-43e6-86ed-c8d1b7714f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;volverSeccionConsignado&quot;)</value>
      <webElementGuid>ec235754-83f1-4257-85c9-748655b1371d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='volverSeccionConsignado']</value>
      <webElementGuid>a6e6b9a9-5fdb-461e-8033-47cf53c2e50f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[4]/button</value>
      <webElementGuid>baef2e57-8efd-4a6d-9ff5-4f663311495b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lunes - Viernes 08:00 - 18:00'])[1]/following::button[1]</value>
      <webElementGuid>a6c7c5bd-f0bf-41a7-a71d-9c20ad75f344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Abierto'])[1]/following::button[1]</value>
      <webElementGuid>65ca0415-333e-4f2f-a8eb-6293c76300a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[2]/preceding::button[1]</value>
      <webElementGuid>21937e5a-c10e-493c-b3da-121bc004c59b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'volverSeccionConsignado', '&quot;', ')')])[1]/preceding::button[2]</value>
      <webElementGuid>db48296a-817e-457b-84ff-edd43f2ec043</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/button</value>
      <webElementGuid>45b30a3a-f641-4f60-b8b1-432082c8999e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'volverSeccionConsignado' and (text() = 'VOLVER' or . = 'VOLVER')]</value>
      <webElementGuid>8270a458-749a-49d4-9c63-def8cfa5ccc3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='volverSeccionQueEnvias']</value>
      <webElementGuid>b01abae2-81df-4772-bb05-402212b49ec4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-quien-recibe/div/div[8]/button</value>
      <webElementGuid>47e25f6b-7fdd-405b-b409-9c7167caabeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='MUY PRONTO'])[1]/following::button[1]</value>
      <webElementGuid>a04feb8c-7103-46a2-8875-50f2968dd8a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[2]/preceding::button[2]</value>
      <webElementGuid>2b1e64ee-44f3-44a2-a5cc-84b4bd308d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='VOLVER']/parent::*</value>
      <webElementGuid>e5f741e6-aaaf-42ef-9a81-d18adcae3b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/button</value>
      <webElementGuid>ab6d2d44-47ba-4a6a-b2a7-248cc8f8c9d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'volverSeccionQueEnvias' and (text() = 'VOLVER' or . = 'VOLVER')]</value>
      <webElementGuid>4ce73dd1-3c09-4e40-b1ae-d10ec5b45e4c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
