<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_OLVA REAL PLAZA PURUCHUCOATE - AV JAVIE_119dc0</name>
   <tag></tag>
   <elementGuidId>2b398ce5-35a7-47aa-9cef-dffc3d4d7b90</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[3]/div[4]/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.item.font-13.ng-star-inserted.hover</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be569389-e3ca-4d63-a4a8-c8650da34c01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item font-13 ng-star-inserted hover</value>
      <webElementGuid>0070c040-7e4f-4d22-806a-7c73527d3c94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OLVA REAL PLAZA PURUCHUCOATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO AbiertoLunes - Viernes 08:00 - 18:00</value>
      <webElementGuid>aa0d7044-ac00-4370-be36-4463374239d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[1]/app-formulario-envio[@class=&quot;ng-star-inserted&quot;]/div[@class=&quot;row px-4 pxc&quot;]/div[@class=&quot;col-personalized-3 margin-top-responsive&quot;]/div[@class=&quot;shadow border-card contenedor-div&quot;]/div[@class=&quot;row ng-star-inserted&quot;]/div[@class=&quot;col-md-12 row justify-content-center ng-star-inserted&quot;]/div[@class=&quot;col-md-12 row mt-2 ng-star-inserted&quot;]/div[@class=&quot;col-md-6 scroll-content&quot;]/div[@class=&quot;item font-13 ng-star-inserted hover&quot;]</value>
      <webElementGuid>046e1d22-a0cb-46d7-b8df-2e8e79867bf9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[3]/div[4]/div[2]/div</value>
      <webElementGuid>8809c2b6-35b8-40e9-a2b9-c1a4e7682bf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Leaflet'])[1]/following::div[2]</value>
      <webElementGuid>68f51457-ce29-41f3-b194-d2f457d164b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>96fd8b1c-d7b1-4137-a287-df061cea7844</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'OLVA REAL PLAZA PURUCHUCOATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO AbiertoLunes - Viernes 08:00 - 18:00' or . = 'OLVA REAL PLAZA PURUCHUCOATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO AbiertoLunes - Viernes 08:00 - 18:00')]</value>
      <webElementGuid>19b16fc0-ef95-41e0-ae1c-b8ba30938e4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
