<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_LIMA - LIMA - SAN LUIS</name>
   <tag></tag>
   <elementGuidId>2a92c466-6a21-42e7-80c2-495614cc9215</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='opcion.codUbigeo'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>64b40061-51b0-451f-b8ed-2c97c06701c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opcion.codUbigeo</value>
      <webElementGuid>c29a8cf1-5240-496a-9ac8-c50e13d6e991</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-origen-destino ng-star-inserted hover</value>
      <webElementGuid>1cbf5955-5d05-41e8-915f-d79840430b49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> LIMA - LIMA - SAN LUIS </value>
      <webElementGuid>cd465648-cd79-4b67-b545-52faf85a3c8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;autocompleteOrigen&quot;)/div[@id=&quot;opcion.codUbigeo&quot;]</value>
      <webElementGuid>1b17450e-706a-4f27-b3f7-d9c0d470ffa2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//div[@id='opcion.codUbigeo'])[5]</value>
      <webElementGuid>5c98b24d-7993-4846-8ef1-c0bdff3bbdf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='autocompleteOrigen']/div[5]</value>
      <webElementGuid>d7bc7b69-bd1d-41cc-92fb-d8a1c32c2660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='LIMA - CAÑETE - SAN LUIS'])[1]/following::div[1]</value>
      <webElementGuid>060ec541-2451-4fa7-a1bf-e206df7974cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CAJAMARCA - SAN PABLO - SAN LUIS'])[1]/following::div[2]</value>
      <webElementGuid>71d52d4f-fc09-4fac-bdfc-e3f7042b2a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[2]/preceding::div[1]</value>
      <webElementGuid>34141dcc-93a4-4f96-9f3d-084064ad796c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CONTINUAR'])[3]/preceding::div[1]</value>
      <webElementGuid>845ef0bb-bbf2-4641-be34-5c5e58975579</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LIMA - LIMA - SAN LUIS']/parent::*</value>
      <webElementGuid>455f19d7-b349-405a-a8ab-9eb6328cdb6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]</value>
      <webElementGuid>108afde4-4881-4ba7-94a7-76e824fa308a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'opcion.codUbigeo' and (text() = ' LIMA - LIMA - SAN LUIS ' or . = ' LIMA - LIMA - SAN LUIS ')]</value>
      <webElementGuid>754fbc11-49b8-4f6a-b5bb-9c65f5b61ca5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
