<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Hasta 1 KgEjemEjemplo Ropa, bisutera, r_6e53fb</name>
   <tag></tag>
   <elementGuidId>28c62b88-b04a-4fc4-8b91-2f3d519510c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pesoUnKilo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#pesoUnKilo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>0e1c26df-63e9-45e2-94bb-bbd12582352b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>pesoUnKilo</value>
      <webElementGuid>bd87550a-fc7f-48d9-a49f-bc4505a44550</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>justify-responsive align-items-center div-width-responsive div-peso-paquete-seleccionado</value>
      <webElementGuid>8b94cb52-017f-450e-8767-601e346d3bbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>e3335db1-0119-482f-9366-8364e46dde70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hasta 1 KgEjemEjemplo: Ropa, bisutería, reloj,lentes, etc.</value>
      <webElementGuid>14378534-e243-4440-927b-c46640b1d55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pesoUnKilo&quot;)</value>
      <webElementGuid>df8525cb-d4d9-4beb-9e10-b1ee6c3cec9a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='pesoUnKilo']</value>
      <webElementGuid>93467885-4cc5-4e25-927c-e063bd3683ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[3]/div</value>
      <webElementGuid>29434260-7288-427b-b6b3-4b7e8a462e8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona el peso que mejor se ajuste a tu envío.'])[1]/following::div[2]</value>
      <webElementGuid>2b1006d5-ef0e-42c1-808a-9247c2fe1a73</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tamaño del envío'])[1]/following::div[3]</value>
      <webElementGuid>57a41aef-243d-412a-9f17-cc60a53169b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div</value>
      <webElementGuid>cc0cdf2e-6af2-4e88-ab5e-5c0764d05403</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'pesoUnKilo' and (text() = 'Hasta 1 KgEjemEjemplo: Ropa, bisutería, reloj,lentes, etc.' or . = 'Hasta 1 KgEjemEjemplo: Ropa, bisutería, reloj,lentes, etc.')]</value>
      <webElementGuid>be63e085-58ec-42a1-bcf2-3dac1bb8cc16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
