<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Ejem</name>
   <tag></tag>
   <elementGuidId>4f0b829d-d872-4d98-982d-d7d86b5a7f2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='pesoUnKilo']/div[2]/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.justify-content-center.d-flex</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9b9fc741-2a92-4485-8e91-5679e391ba4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>justify-content-center d-flex</value>
      <webElementGuid>52694c59-1ae0-4309-99fe-4fb1f707e54e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ejem</value>
      <webElementGuid>53c84beb-d473-4582-9640-727b6ca5cf8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;pesoUnKilo&quot;)/div[@class=&quot;extra-info ng-star-inserted&quot;]/div[1]/div[@class=&quot;justify-content-center d-flex&quot;]</value>
      <webElementGuid>c14b43c5-7273-483a-9269-42fc02300a62</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pesoUnKilo']/div[2]/div/div</value>
      <webElementGuid>b21c09da-0943-4d9b-866c-abe8619a9e2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kg'])[1]/following::div[3]</value>
      <webElementGuid>3fea2579-81db-4240-87ee-bf001616d9ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ropa, bisutería, reloj,'])[1]/preceding::div[1]</value>
      <webElementGuid>aa1ec2bb-2083-4f9a-9ec7-46c3ef87e2c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/div</value>
      <webElementGuid>9a759e62-7d7d-4982-b66f-98487e3b1d08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Ejem' or . = 'Ejem')]</value>
      <webElementGuid>99b5905d-e1c9-48c9-a5d4-8b1e41cdce5f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
