<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_CONTINUAR_btn-icon ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>c94594cc-4c6b-44f5-b06c-d09f3606feec</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='avanzarToSelectOrigen']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.btn-icon.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>522aaca8-d12f-46e0-962f-3d54b8063d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icon_arrow_right.png</value>
      <webElementGuid>f9142c32-9d01-4005-b5a0-eb29bf325f17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>fcc9d40b-0a6f-484f-8cc8-590d7cdd2e86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>e17adf38-58c1-4ac6-8bdc-da9011134fce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon ng-star-inserted</value>
      <webElementGuid>6161e750-3688-4c3b-ab0f-bdfdbda22b15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avanzarToSelectOrigen&quot;)/img[@class=&quot;btn-icon ng-star-inserted&quot;]</value>
      <webElementGuid>4e8eda06-6928-48cf-8635-9214e79aa8bd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='avanzarToSelectOrigen']/img</value>
      <webElementGuid>ae083223-adb3-476d-b001-80ddb190070c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/img</value>
      <webElementGuid>a0ca116a-87ab-4d2d-aed1-78877bfeb50e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/icon_arrow_right.png']</value>
      <webElementGuid>2d87c3c8-e38f-458a-92ce-28999742cb1a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
