<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_GUARDAR_btn-icon ng-star-inserted</name>
   <tag></tag>
   <elementGuidId>5edfa562-4380-4250-acea-616e935fcc44</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='guardarCliente']/img</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img.btn-icon.ng-star-inserted</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b5dd542d-089a-49d5-acff-da049bc2b782</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icon_arrow_right_grey.png</value>
      <webElementGuid>92b89123-7eed-4c60-98ec-d11d3614d013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>9b65d6e6-c56f-4446-a074-ece97e04c743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>bfbec917-2617-4ba7-ad05-0118e14a5785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon ng-star-inserted</value>
      <webElementGuid>9e07e98c-003d-442a-893b-3d15fb99e6fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guardarCliente&quot;)/img[@class=&quot;btn-icon ng-star-inserted&quot;]</value>
      <webElementGuid>d3d00c0e-c835-441e-aca8-ba644686f137</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='guardarCliente']/img</value>
      <webElementGuid>ec945493-5540-409e-9281-ec6fa1f65ba1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/img</value>
      <webElementGuid>0ce19a6e-3d98-438c-8538-d4031f5bcd2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/icon_arrow_right_grey.png']</value>
      <webElementGuid>80cf8dd8-d634-47b2-bdf5-f3879f6190d0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
