<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Ingresa el destino de tu envo_cancelarDestino</name>
   <tag></tag>
   <elementGuidId>7203c0da-45dc-4fa8-81ee-cc9b3b92d436</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='cancelarDestino']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cancelarDestino</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>f21cc7e2-c4d5-4964-86f2-6b7df8ffdde5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cancelarDestino</value>
      <webElementGuid>65284d4e-5aa9-445e-9f12-c709b5f6b268</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icon_cancel_grey_2.png</value>
      <webElementGuid>d49e9b9d-2b6d-4dec-a580-4762c061d491</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>ac662ec3-56a5-41b7-89f5-5eaf29b22198</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>dea96c68-b388-40e7-9f7a-244f665ae433</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-fluid</value>
      <webElementGuid>8b76b904-8112-46bd-a0cf-fe419fa3139b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelarDestino&quot;)</value>
      <webElementGuid>884622e9-92d2-4a7e-a377-bc2818db565e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='cancelarDestino']</value>
      <webElementGuid>56c903f3-9da1-481f-ac7a-b139edf95151</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-lista-ubigeo-destino/div/div/div/div/img</value>
      <webElementGuid>36a57eb1-e09e-4907-b32c-29f1d2f2ea62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-lista-ubigeo-destino/div/div/div/div/img</value>
      <webElementGuid>5aedebd2-1490-4e0a-8a35-ef09203f16af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'cancelarDestino' and @src = 'assets/images/icon_cancel_grey_2.png']</value>
      <webElementGuid>8bc7ebde-1327-43ba-81aa-4ec157060652</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
