<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NUMERO DE PEDIDO_frmPreventaBusctxtNroPedido</name>
   <tag></tag>
   <elementGuidId>97a8283a-ed46-4983-b72d-344fe4040c6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmPreventaBusc:txtNroPedido']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2242579d-46f4-4003-86f7-05cb6eb4a30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmPreventaBusc:txtNroPedido</value>
      <webElementGuid>e49de4d0-694e-4130-8e4c-fee2ea16df2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmPreventaBusc:txtNroPedido</value>
      <webElementGuid>1b45d40f-0989-4395-9a65-3553926ff92d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e3ab5993-741d-4954-9900-c15dd00d17f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>eba73792-d69c-461d-b3d6-a64d0c881a01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeydown</name>
      <type>Main</type>
      <value>                                          if(event.keyCode === 13){                                              if(document.getElementById('frmPreventaBusc:txtNroPedido').value.trim().length !== 0){                                                 rcEnviarCodigo();                                                 this.value = '';                                                                                                return false;                                                                                               }else{                                                 rcSelectPreventa();                                                 return false;                                                }                                          }else if(event.keyCode === 40){                                              javascript:recorrer(event, 'tabDivPreventa', 'tblPreventaWdg', '#frmPreventaBusc\\:tblPreventa');                                          }</value>
      <webElementGuid>23296dda-08da-448c-8637-9282528e3b76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-inputfield ui-inputtext ui-widget ui-state-default ui-corner-all ui-state-focus ui-state-hover</value>
      <webElementGuid>e8c17d2d-682a-42ec-a76b-f23ec4792fd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>textbox</value>
      <webElementGuid>7947d006-5edb-4330-a889-90b15a528264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>93ac5155-733f-4bdd-be85-32f035fa787d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-readonly</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>d2f32d1d-ea19-4416-aee8-1bae7af27271</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmPreventaBusc:txtNroPedido&quot;)</value>
      <webElementGuid>addf8773-0522-47bc-a8f9-9d16546beff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Negativos/validaciones_casos/iframe_Reporte_iframePrincipal</value>
      <webElementGuid>8d8c448d-91fa-44e8-bac3-fd72b4285450</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmPreventaBusc:txtNroPedido']</value>
      <webElementGuid>6a004dc3-2fa2-42bc-a4a0-c546117e2efc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='frmPreventaBusc:pnlGrdEnviosPistoleados']/tbody/tr/td/input</value>
      <webElementGuid>6ecc52d5-d06f-4886-9f9b-bbf0bcc3f97d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/table/tbody/tr/td/input</value>
      <webElementGuid>fc2067ab-c2b8-4120-a36d-99fa16fbc337</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmPreventaBusc:txtNroPedido' and @name = 'frmPreventaBusc:txtNroPedido' and @type = 'text']</value>
      <webElementGuid>6c918a21-9161-4d79-8ca1-8fde436446e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
