<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Acceder para continuar a Olva_frmLogi_81423f</name>
   <tag></tag>
   <elementGuidId>4d473586-4797-4a96-9a96-b77efd7afc9c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='frmLogin:loginButton']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bfcd6479-ff58-498b-be7c-1c027cdaa256</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>frmLogin:loginButton</value>
      <webElementGuid>154cda55-93a5-431c-ab79-98c9eefa94d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>235dcb65-5cba-4a20-82e0-d5e90b64ed84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>frmLogin:loginButton</value>
      <webElementGuid>8e73e5a5-66f0-457b-a192-66df0dbb7e7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Acceder </value>
      <webElementGuid>d21e4e53-21c5-44fa-b973-d844cf503a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmLogin:loginButton&quot;)</value>
      <webElementGuid>2d1a7576-0321-408f-b971-78b71ee58536</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='frmLogin:loginButton']</value>
      <webElementGuid>e7961997-adc5-4909-96ae-c6974feb30e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='frmLogin:pnlLogin_content']/table/tbody/tr[3]/td/input</value>
      <webElementGuid>f0667aa7-9568-4909-9e84-a81533d50fea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[3]/td/input</value>
      <webElementGuid>64abd0ca-c9c4-4418-b92b-a62fe19386d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'frmLogin:loginButton' and @type = 'submit' and @name = 'frmLogin:loginButton']</value>
      <webElementGuid>bbeddb59-521c-49fb-b7b5-a7eb70f66aaa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
