<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DIRECCIN EXACTA_inputReferenciaDestinoComp</name>
   <tag></tag>
   <elementGuidId>f78460bb-14d3-4776-bdc2-7da79c7b40a4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputReferenciaDestinoComp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputReferenciaDestinoComp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>284b1e0a-68b9-4f58-ba11-2dabe13187ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd616b2d-3f06-4c07-ba5d-c646d5d67b4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>50abe7db-efd1-49b0-b38b-d5d2d9db1da5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputReferenciaDestinoComp</value>
      <webElementGuid>9ad9276c-b3a7-42b4-afd8-62989a4eb2c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputReferenciaDestinoComp</value>
      <webElementGuid>b2e8db9b-510c-48de-9ecd-fb1e14537391</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>5019ac5d-a2fe-421f-99aa-c2571b1cc2f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>0c0b8a5e-82a7-4727-a467-c7790fb14c99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputReferenciaDestinoComp</value>
      <webElementGuid>f2c49b54-83ee-4f18-903b-996e8cbc16ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputReferenciaDestinoComp&quot;)</value>
      <webElementGuid>9bafca29-336c-49ca-bb4f-f3756fdedd7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputReferenciaDestinoComp']</value>
      <webElementGuid>e51df90e-cbb9-4068-be0d-5655546d3d7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-tipo-entrega/div[2]/div[3]/div/div[3]/input</value>
      <webElementGuid>f22769b6-b89b-405f-b15d-8aa3c8308234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>feceb069-2671-4c75-aec2-9b10f14a9d66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputReferenciaDestinoComp']</value>
      <webElementGuid>0762db04-42f3-485a-a6a9-c27e76179e4f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
