<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Escriba su primer apellido igual al d_19137b</name>
   <tag></tag>
   <elementGuidId>430b8d4e-0837-4140-b5ea-aa11f9b3ef8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputConfirmApellido</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputConfirmApellido']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0d463f4d-ed6b-44c3-8f15-180b001df996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>dc3bc164-ff2f-4f65-8995-58cfa06e4834</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>33bcd36e-9b27-43f2-9f72-c17034d60039</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputConfirmApellido</value>
      <webElementGuid>0cddea7a-2f53-45c0-a273-1f59ee0b63d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>99403e2f-69df-4eb6-ab48-dfc49d22325b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>5967b631-af81-448f-9533-3cdeab0c7f86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputConfirmApellido&quot;)</value>
      <webElementGuid>e2e1d142-c4c6-4571-b639-7ce9492456e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputConfirmApellido']</value>
      <webElementGuid>2ec88ff9-c88a-45f4-8f88-fab7757756fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-validacion-apellido-modal/div/div/div[2]/div/input</value>
      <webElementGuid>4a249544-4915-4547-9aae-6456a98e7cfa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-validacion-apellido-modal/div/div/div[2]/div/input</value>
      <webElementGuid>9edfa7a0-b722-4b9c-9828-f406ef1456a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputConfirmApellido']</value>
      <webElementGuid>b9cf5979-fd74-4e3a-967e-690e8f4a585d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
