<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_DESTINO</name>
   <tag></tag>
   <elementGuidId>a773c736-791f-49f3-bb1a-07abdce7d4b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='seleccionaDestino']/div/small[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.position-a > small:nth-of-type(2)</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>862185ff-e9ec-4c76-9a62-4871ce81fbc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>DESTINO</value>
      <webElementGuid>21810963-53b0-4615-844d-9f8654671750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seleccionaDestino&quot;)/div[@class=&quot;position-a&quot;]/small[2]</value>
      <webElementGuid>5acd999a-5046-471c-ad94-9be398ea9c27</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='seleccionaDestino']/div/small[2]</value>
      <webElementGuid>604862d2-c515-4ea3-9f96-4ec3db37c102</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESE DESTINO'])[1]/following::small[1]</value>
      <webElementGuid>5147bdc6-9128-429b-8666-d50748f6ed8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hacia:'])[1]/following::small[2]</value>
      <webElementGuid>661ba191-4457-4376-ab65-4865e0cfafd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forma de pago'])[1]/preceding::small[1]</value>
      <webElementGuid>977d8c04-7e7e-41e2-ad29-5e2c9dc94744</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ofrecemos dos formas de pago para cada envío registrado, selecciona la que prefieras.'])[1]/preceding::small[1]</value>
      <webElementGuid>a43ed3ee-36c8-45f0-9e52-1875cba1c922</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/small[2]</value>
      <webElementGuid>9d016d94-4996-4a26-9045-e7095457e787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'DESTINO' or . = 'DESTINO')]</value>
      <webElementGuid>c0693a7e-d13e-4359-9423-e97188ad5a60</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='DESTINO']/parent::*</value>
      <webElementGuid>11aaa857-29a1-4b64-a988-be7432c5da18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/small[2]</value>
      <webElementGuid>83d96535-803c-4dcd-9800-b0e9ca7013cb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
