<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Grabar</name>
   <tag></tag>
   <elementGuidId>6f37bdeb-bd66-4ec1-9c0d-3c71d9f94493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='frmConfHost:j_idt56']/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>8920765a-da19-4070-ba5b-15fd741cf816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-button-text ui-c</value>
      <webElementGuid>4ccd3410-2a45-4c68-982b-273e922a58d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Grabar</value>
      <webElementGuid>9c05c13b-f9d6-484b-bec8-00184691cda2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frmConfHost:j_idt56&quot;)/span[@class=&quot;ui-button-text ui-c&quot;]</value>
      <webElementGuid>f08f62df-4e49-4e5e-a221-7cbb774df98e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Negativos/validaciones_casos/iframe__iframePrincipal</value>
      <webElementGuid>8a3f7018-b39d-4f90-a2d2-9e5e948cd1c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='frmConfHost:j_idt56']/span[2]</value>
      <webElementGuid>1ccb8889-ba82-46b1-ade4-74a537999f36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Host:'])[1]/following::span[4]</value>
      <webElementGuid>be044e38-7e26-4813-a564-b6c3ad8aa46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Configurar Host'])[1]/following::span[5]</value>
      <webElementGuid>e05d4f25-12ff-48fe-adbc-da3501e8b081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Salir'])[1]/preceding::span[2]</value>
      <webElementGuid>1b364058-6dba-4105-92fd-f6ff72045a2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nuevo Host'])[1]/preceding::span[3]</value>
      <webElementGuid>37f17a49-97cd-4d2e-947d-60fc9c9890f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Grabar']/parent::*</value>
      <webElementGuid>bcdfa1c9-e1a7-4c59-8c74-fc70ee863a4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/button/span[2]</value>
      <webElementGuid>2ab096d8-b988-443b-80bf-cd0ae36a7e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Grabar' or . = 'Grabar')]</value>
      <webElementGuid>638f4ea9-c408-4a54-a142-ce9c19dfb62c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
