<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_CONTINUAR_btn-icon</name>
   <tag></tag>
   <elementGuidId>81e8cc5b-62af-4d29-9a31-fb657fb45493</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.btn-icon</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[7]/button[2]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;CONTINUAR&quot;i] >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>4de965e3-9d05-4849-8712-56faf8552726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icon_arrow_right.png</value>
      <webElementGuid>d8993fd1-4f53-419a-97fd-23046d4634e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>0c7cdadd-b21a-4e67-a132-24f2f124ee58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f5c14b3b-e751-4dd4-be5c-f480003a2677</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon</value>
      <webElementGuid>01b6357b-09d7-4d0e-9627-a2c058e909f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[1]/app-formulario-envio[1]/div[@class=&quot;row px-4 pxc&quot;]/div[@class=&quot;col-personalized-2&quot;]/div[@class=&quot;shadow border-card contenedor-div&quot;]/div[@class=&quot;row ng-dirty ng-touched ng-valid&quot;]/div[@class=&quot;contenedor mt-12 p-75&quot;]/button[@class=&quot;boton px-3 custom-btn&quot;]/img[@class=&quot;btn-icon&quot;]</value>
      <webElementGuid>ced7aad6-1d9f-4285-bb55-e8e176999da9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[7]/button[2]/img</value>
      <webElementGuid>da8a335e-f8e8-4a60-9ef4-c2d454730d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/img</value>
      <webElementGuid>b87c7535-3663-4439-b208-dfa167f4a37e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/icon_arrow_right.png']</value>
      <webElementGuid>a44cbf26-8fd5-47a6-8929-5a520c3009ef</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
