<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_TiendasAgentes Olva_leaflet-marker-icon_4ea37c</name>
   <tag></tag>
   <elementGuidId>a7aff42d-7c17-49c5-900c-9f3fd920476b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.leaflet-marker-icon.leaflet-zoom-animated.leaflet-interactive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='mapa']/div/div[4]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Marker&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>bdb5c4ae-c5bc-4f34-b0b1-531087ac7f7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png</value>
      <webElementGuid>09e4e16c-0730-4a2a-b865-0dcd7e201f51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>leaflet-marker-icon leaflet-zoom-animated leaflet-interactive</value>
      <webElementGuid>0d0aad06-f945-4877-b626-e969d462da08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Marker</value>
      <webElementGuid>89c584d1-1667-405f-ae18-0491ec2c08b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>417cfaa3-9e92-475e-8ebd-86610081636b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c5d4a015-cc2f-43b8-a352-eb9ab7adcba1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>leaflet-tooltip-55</value>
      <webElementGuid>130b0ae7-33ae-4015-9c8b-9bfeb2bb97de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mapa&quot;)/div[@class=&quot;leaflet-pane leaflet-map-pane&quot;]/div[@class=&quot;leaflet-pane leaflet-marker-pane&quot;]/img[@class=&quot;leaflet-marker-icon leaflet-zoom-animated leaflet-interactive&quot;]</value>
      <webElementGuid>585afd61-d7af-47a0-ad47-97110d44c330</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='mapa']/div/div[4]/img</value>
      <webElementGuid>0654e3fe-99bb-41ac-ba57-583ddfa263bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Marker']</value>
      <webElementGuid>e1a29f5f-a2f5-4a19-a7b9-7130ee4711ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/img</value>
      <webElementGuid>bdf8f385-6233-4495-9461-0aea29715486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://unpkg.com/leaflet@1.9.4/dist/images/marker-icon.png' and @alt = 'Marker']</value>
      <webElementGuid>746b3749-0263-4060-b8ee-74ca863159be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
