<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_GUARDAR</name>
   <tag></tag>
   <elementGuidId>4567d41a-a1bd-44df-b446-f05f4bc33acf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='guardarCliente']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#guardarCliente</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f051e705-e4fa-4d23-a32f-2c6b21dbe07f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>guardarCliente</value>
      <webElementGuid>08884c15-b6c2-4888-97e0-e6bb284a2992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>px-3 custom-btn boton</value>
      <webElementGuid>d5d5544d-8727-4b24-9de6-b6438e3c61e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-ng-class</name>
      <type>Main</type>
      <value>[object Object]</value>
      <webElementGuid>2d76e85f-5566-45f3-8fd3-28d4243435cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GUARDAR</value>
      <webElementGuid>201c55ac-e075-49a0-9173-e321406638ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;guardarCliente&quot;)</value>
      <webElementGuid>e31a40a6-c564-4c45-85cc-5ceedc8228ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='guardarCliente']</value>
      <webElementGuid>55f37f91-6b02-4824-b7f5-aaa5a81cc165</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[7]/button[2]</value>
      <webElementGuid>e1e84d4f-1b31-4d74-b8cd-add55cd7260e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[1]/following::button[1]</value>
      <webElementGuid>f7944a0c-7e47-4f62-ade7-49046f5d83b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='CELULAR'])[1]/following::button[2]</value>
      <webElementGuid>1c0503fa-b1d1-457a-a643-be775c231d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona origen y destino'])[1]/preceding::button[1]</value>
      <webElementGuid>89d83e00-49a5-4668-a430-0f31a420229c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button[2]</value>
      <webElementGuid>91744b58-ef85-475d-9cc6-064b080b90d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'guardarCliente' and (text() = 'GUARDAR' or . = 'GUARDAR')]</value>
      <webElementGuid>c090e443-6d3a-4703-916d-bf29800aa67f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
