<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Cancel_visaNetJS</name>
   <tag></tag>
   <elementGuidId>4abf5794-b526-42ff-9f16-a3606df9149d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='visaNetJS']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#visaNetJS</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>04125db2-6123-4057-a843-e9bbc3754b58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>visaNetJS</value>
      <webElementGuid>07ceb29d-dbec-4171-aa23-07f31f8d4791</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3ae1bf2b-d42f-41ba-a33b-0ffc7c5abac0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d0b0204c-1a43-4c63-abb6-122b159ab984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://static-content-qas.vnforapps.com/v2/visanet.html?0.0725566976024774&amp;qa=true</value>
      <webElementGuid>999efe0e-b3b4-421c-b515-f16b40ef36be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;visaNetJS&quot;)</value>
      <webElementGuid>69f84bf1-d479-401d-a9ed-e5e18eed202c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='visaNetJS']</value>
      <webElementGuid>ed772e38-a719-494f-bc49-55a84456788d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='visaNetWrapper']/iframe</value>
      <webElementGuid>a6ffdef4-0ed4-4090-b398-2debe9b5b87d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/iframe</value>
      <webElementGuid>fd3ddef1-1775-4258-a548-82ff0dbf2be3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'visaNetJS' and @src = 'https://static-content-qas.vnforapps.com/v2/visanet.html?0.0725566976024774&amp;qa=true']</value>
      <webElementGuid>01798f83-7c9b-4c36-93e4-39fbf63ecdbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
