<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_CELULAR_inputEmailClienteCrear</name>
   <tag></tag>
   <elementGuidId>9b8fb7e5-778e-4e5b-84c7-486c4d2c9ceb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputEmailClienteCrear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputEmailClienteCrear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>59419a1f-12bb-42c4-a621-ef8b8e176260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dda6ea5a-2135-4684-8095-aa02b85d80f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputEmailClienteCrear</value>
      <webElementGuid>477e8c94-d295-4839-bd54-6abe60402b61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputEmailClienteCrear</value>
      <webElementGuid>34ae0741-10bc-4d2d-9a64-eae109b8181d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>9011b614-189a-47b2-b0f7-b3bb61973ab1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputEmailClienteCrear</value>
      <webElementGuid>d87dafde-6e1d-4c59-a98d-9e53e856274a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputEmailClienteCrear&quot;)</value>
      <webElementGuid>b4dca85c-7343-4142-b6a1-e2e93df3508c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputEmailClienteCrear']</value>
      <webElementGuid>ac00d5f4-f52a-4eff-861b-1edb33d6133b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[7]/div/div/input</value>
      <webElementGuid>d1b12c2d-9d39-47f4-ba79-ab4e8b1f01eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/div/div/input</value>
      <webElementGuid>0c6e8a4b-1793-4e8d-aaff-9993b77b235f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputEmailClienteCrear']</value>
      <webElementGuid>147e543d-66ae-4451-8e96-db6bfb7fc92f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
