<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_FACTURA_inputNroDocumentoClienteCrear</name>
   <tag></tag>
   <elementGuidId>928993bd-7137-4015-a3ed-3dddb46d127f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputNroDocumentoClienteCrear']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputNroDocumentoClienteCrear</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8bdd5205-47cb-4a72-8ca1-cb1e8500acaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c6540c4b-84ef-4e61-b5b9-e30b9429caaf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputNroDocumentoClienteCrear</value>
      <webElementGuid>5c027c39-b76f-4659-8201-dd8f8a31874c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputNroDocumentoClienteCrear</value>
      <webElementGuid>434a10bc-54e8-44f5-ad30-61c6cca1e4ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>63e9756d-228c-4195-acc7-6130c3091159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputNroDocumentoClienteCrear</value>
      <webElementGuid>ecf8639d-9b59-4795-a8db-aa1b587a723b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>9</value>
      <webElementGuid>2a0db8de-39df-420e-b20e-7e3585a539bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputNroDocumentoClienteCrear&quot;)</value>
      <webElementGuid>3d4b6fe0-1aa0-4222-b11e-b66dd6e2410a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputNroDocumentoClienteCrear']</value>
      <webElementGuid>d627a72c-ecc0-47c7-a0c7-bd9fc65e2022</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[4]/div[2]/div/input</value>
      <webElementGuid>7059ea0f-947a-454a-bbfc-72b424f3e92b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>5559895c-e967-4b4a-850c-8e2f7f79be96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputNroDocumentoClienteCrear']</value>
      <webElementGuid>b5912bc6-33fb-4a0f-9cd3-6a1c100b2e83</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
