<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECCIONE TIENDA COMAS - CA SEGUNDO_6454ec</name>
   <tag></tag>
   <elementGuidId>6c37b734-6a8c-4146-9e38-3a6a3ae6c5e0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOficinasRetornoCargo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectOficinasRetornoCargo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>6ca25dfc-81d0-4626-b653-226793de47a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>e6aedd68-9771-4949-b043-46815660df8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>bf918198-05fd-45c9-a935-43f5591bb10e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-valid ng-dirty ng-touched</value>
      <webElementGuid>5f3adf1b-65ad-4161-a29d-e83d9a11da20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECCIONE TIENDA COMAS - CA SEGUNDO ROCA NRO 374 URBANIZACION EL RETABLO ETAPA 4 (AL COSTADO DEL POLICLINICO MICAELA BASTIDA)  COMAS - AV UNIVERSITARIA NORTE NRO 6971 URBANIZACION SANTA LUZMILA  </value>
      <webElementGuid>a4bbbfad-f4f4-4f23-b80e-c6d7ad21403a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOficinasRetornoCargo&quot;)</value>
      <webElementGuid>df8ca951-29fd-4cc1-a776-c40146fa7da7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOficinasRetornoCargo']</value>
      <webElementGuid>e52ebe36-0597-4dcc-9a83-22018acf5406</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div/div[2]/select</value>
      <webElementGuid>7bd7be60-8b0c-41ec-9c0a-45b5dddd5924</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESE EL DESTINO DEL CARGO'])[1]/following::select[1]</value>
      <webElementGuid>892487bc-ccd8-460b-993f-ab707a4130bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops, consolas, etc'])[2]/following::select[1]</value>
      <webElementGuid>9d3000f9-e383-43c0-bece-16742c209504</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[1]</value>
      <webElementGuid>bd04c7b3-2acb-46cb-b082-8c59d3b8c662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::select[1]</value>
      <webElementGuid>1a21414e-ce3f-461b-a654-007b3afd7ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/select</value>
      <webElementGuid>8af4c930-0b41-4ab9-8ad8-4ca5bb641bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOficinasRetornoCargo' and (text() = 'SELECCIONE TIENDA COMAS - CA SEGUNDO ROCA NRO 374 URBANIZACION EL RETABLO ETAPA 4 (AL COSTADO DEL POLICLINICO MICAELA BASTIDA)  COMAS - AV UNIVERSITARIA NORTE NRO 6971 URBANIZACION SANTA LUZMILA  ' or . = 'SELECCIONE TIENDA COMAS - CA SEGUNDO ROCA NRO 374 URBANIZACION EL RETABLO ETAPA 4 (AL COSTADO DEL POLICLINICO MICAELA BASTIDA)  COMAS - AV UNIVERSITARIA NORTE NRO 6971 URBANIZACION SANTA LUZMILA  ')]</value>
      <webElementGuid>4a78f1ce-3be0-4b24-87bb-582241c9ded9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
