<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECCIONE TIENDA ATE - AV JAVIER PR_1a42df</name>
   <tag></tag>
   <elementGuidId>fddc97a4-6d84-49a7-ae40-92e213439953</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOficinasRetornoCargo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectOficinasRetornoCargo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eee5fe29-25ce-4f64-97c5-4b4d8100598f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>bbf7e573-568d-4341-8950-97f7f0b14755</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>1c529263-2e70-48f9-979c-9c723ec3877c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>fb3e0314-c882-4e2a-878d-497596a32397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>8c8091ee-58ac-4b46-be63-6147ee95d98f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECCIONE TIENDA ATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO   ATE - AV CARRETERA CENTRAL 7.5 KM S/N   ATE - CA 1 DE MAYO MZ 11 LTE 10 URB SAN GREGORIO   ATE - AV LA ESTRELLA S/N URB SANTA CLARA ((CENTRO COMERCIAL REAL PLAZA ) AL FRENTE DE TAI LOY)  ATE - AV LOS QUECHUAS S/N URBANIZACION SALAMANCA   ATE - Avenida Nicolás Ayllón, Ate, Perú(AV. CARRETERA CENTRAL 14.8 KM. GLORIA GRANDE LIMA - LIMA - ATE)  ATE - AV LOS QUECHUAS NRO 1485 URB SALAMANCA  </value>
      <webElementGuid>dc2552a7-591d-4dcc-b604-64761874190b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOficinasRetornoCargo&quot;)</value>
      <webElementGuid>41a240e3-ae8c-4458-a1c6-9d1c9ae91b76</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOficinasRetornoCargo']</value>
      <webElementGuid>ab2f175f-fe97-44e5-bc8f-e77ede473879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div/div[2]/select</value>
      <webElementGuid>a9f8e9c7-4bf5-46df-97f9-7c644d9144dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESE EL DESTINO DEL CARGO'])[1]/following::select[1]</value>
      <webElementGuid>9e3cc008-857e-424e-a2d1-56da9b7a613d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops, consolas, etc'])[2]/following::select[1]</value>
      <webElementGuid>158df2a3-0d0c-410b-b050-6f53f4d2c566</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[1]</value>
      <webElementGuid>aa2c38f2-0794-45c9-9e9c-e7e5e8a80661</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::select[1]</value>
      <webElementGuid>0de19dcd-7815-46a0-9c13-52b9319d43de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/select</value>
      <webElementGuid>3d1dcb4d-6ce3-4f4e-a917-db357e4f0f9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOficinasRetornoCargo' and (text() = 'SELECCIONE TIENDA ATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO   ATE - AV CARRETERA CENTRAL 7.5 KM S/N   ATE - CA 1 DE MAYO MZ 11 LTE 10 URB SAN GREGORIO   ATE - AV LA ESTRELLA S/N URB SANTA CLARA ((CENTRO COMERCIAL REAL PLAZA ) AL FRENTE DE TAI LOY)  ATE - AV LOS QUECHUAS S/N URBANIZACION SALAMANCA   ATE - Avenida Nicolás Ayllón, Ate, Perú(AV. CARRETERA CENTRAL 14.8 KM. GLORIA GRANDE LIMA - LIMA - ATE)  ATE - AV LOS QUECHUAS NRO 1485 URB SALAMANCA  ' or . = 'SELECCIONE TIENDA ATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO   ATE - AV CARRETERA CENTRAL 7.5 KM S/N   ATE - CA 1 DE MAYO MZ 11 LTE 10 URB SAN GREGORIO   ATE - AV LA ESTRELLA S/N URB SANTA CLARA ((CENTRO COMERCIAL REAL PLAZA ) AL FRENTE DE TAI LOY)  ATE - AV LOS QUECHUAS S/N URBANIZACION SALAMANCA   ATE - Avenida Nicolás Ayllón, Ate, Perú(AV. CARRETERA CENTRAL 14.8 KM. GLORIA GRANDE LIMA - LIMA - ATE)  ATE - AV LOS QUECHUAS NRO 1485 URB SALAMANCA  ')]</value>
      <webElementGuid>2fe9bdc1-403f-4c8d-bbf4-a27083edc2c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
