<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_FOLIOS  1 FOLIO  2 FOLIOS  3 FOLIOS</name>
   <tag></tag>
   <elementGuidId>d840f603-89fe-4365-8f28-1b84efa18367</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='cantidadFolios']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#cantidadFolios</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5eb845f1-7868-4bb3-b84d-9193d61e220b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cantidadFolios</value>
      <webElementGuid>73488981-3bcf-4f9d-ac81-543cf24b9663</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cantidadFolios</value>
      <webElementGuid>718775d5-0aa6-4bff-917b-a129962fd607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>cantidadFolios</value>
      <webElementGuid>b352c540-a240-43a3-baf9-cf8a6619c3ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>1684bb7f-0266-4be6-9151-d9bef43e78dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>369cb7b6-17ce-4b03-8ce7-a7217d49bb03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> FOLIOS  1 FOLIO  2 FOLIOS  3 FOLIOS </value>
      <webElementGuid>b927c945-3e61-4553-822d-2073acb62666</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cantidadFolios&quot;)</value>
      <webElementGuid>e187f9eb-2886-4af7-9a17-45949c924127</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='cantidadFolios']</value>
      <webElementGuid>8b88853a-3c87-4f6b-b7e2-725cc946d621</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[2]/select</value>
      <webElementGuid>d21dff69-0742-481d-964d-3fe8f485de62</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cantidad de Folios:'])[1]/following::select[1]</value>
      <webElementGuid>0d66b1b9-37ca-4c40-b9de-63addf5b5be8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retorno de Cargo'])[1]/following::select[1]</value>
      <webElementGuid>3cea674c-96d6-4522-9b3d-424901a90385</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿A dónde retornamos el cargo?'])[1]/preceding::select[1]</value>
      <webElementGuid>3d7282e9-1b43-4dba-8462-5971b397f514</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>17e20f49-2a76-4a0a-aa0b-206eb2d54486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'cantidadFolios' and @id = 'cantidadFolios' and (text() = ' FOLIOS  1 FOLIO  2 FOLIOS  3 FOLIOS ' or . = ' FOLIOS  1 FOLIO  2 FOLIOS  3 FOLIOS ')]</value>
      <webElementGuid>10507e9f-6714-4885-83b4-31b7bddd1cc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
