<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingresa el destino de tu envo_inputBu_d7b93a</name>
   <tag></tag>
   <elementGuidId>96382ea2-e499-459c-ac26-281360b875c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputBuscarOrigen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputBuscarOrigen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Busca el punto de llegada&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ad753706-bc66-4180-99cf-d6362f6da61b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>d68552f2-24ad-450e-be6e-69829f64c444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputBuscarOrigen</value>
      <webElementGuid>d0c78c86-b918-4390-9434-824bed7dcddb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f4e8ab89-9574-4fa1-b6c9-8e32369c70bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Busca el punto de llegada</value>
      <webElementGuid>996f1d8e-318f-4f3c-9abd-5bc93482c3c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>5cced26a-ac70-4c5f-be2d-f4f1cbb3b471</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ubigeo-origen ng-pristine ng-valid ng-touched</value>
      <webElementGuid>4f42fc8b-734e-4037-ab7c-c6076538664d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>aedfb31c-7fc5-430b-b074-e2468af0b130</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputBuscarOrigen&quot;)</value>
      <webElementGuid>f27187dc-6443-4e7c-8073-d8860bcd21c9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputBuscarOrigen']</value>
      <webElementGuid>f90f2fa0-b6d7-4433-af62-05fed724be86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-lista-ubigeo-destino/div/div/div/div[2]/div/input</value>
      <webElementGuid>c68a08dc-ffb6-4f6d-93f3-c8f1d106c707</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-lista-ubigeo-destino/div/div/div/div[2]/div/input</value>
      <webElementGuid>935a5233-3fee-45bd-8c6a-abecc176ec29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputBuscarOrigen' and @type = 'text' and @placeholder = 'Busca el punto de llegada']</value>
      <webElementGuid>99920c0e-92de-455b-b7c0-848566aa85a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
