<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Cambiar tipo de entrega</name>
   <tag></tag>
   <elementGuidId>eabf804f-e50e-4813-b98a-97eb8ba4a2d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cambiarTipoEntrega</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='cambiarTipoEntrega']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>46feb7f8-b131-4b5f-b4f2-3440169bf1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cambiarTipoEntrega</value>
      <webElementGuid>11cf2237-a970-4b19-ab38-5393bd526002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>back-red</value>
      <webElementGuid>5088d7f4-817a-490d-a2a5-fed7c3255155</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Cambiar tipo de entrega</value>
      <webElementGuid>772fc3e5-6597-4db4-99b2-75fc11fd8f4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cambiarTipoEntrega&quot;)</value>
      <webElementGuid>37441c8a-4d4a-437c-bc4b-884d77a8cc34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='cambiarTipoEntrega']</value>
      <webElementGuid>b9caadd0-13f0-4279-be95-f4d93ba8b58b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-direccion-peligrosa/div/div/div[2]/button[2]</value>
      <webElementGuid>7424e22b-cdae-4aeb-bd9e-40bb9244b44f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Editar dirección'])[1]/following::button[1]</value>
      <webElementGuid>9f857bb7-db7f-4dc3-ad54-2f0aa99dcdea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Zona sin cobertura'])[1]/following::button[2]</value>
      <webElementGuid>aa4ea1fe-1f88-45d9-9b2a-629ddf9725d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'cambiarTipoEntrega', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>d05fac08-0bc7-4130-aeb4-0fceeaef47de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cambiar tipo de entrega']/parent::*</value>
      <webElementGuid>ede580dc-ad8a-4a1e-9b2f-002e45668648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button[2]</value>
      <webElementGuid>bbd7ed60-c8cd-4556-8944-0b3f7b027a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'cambiarTipoEntrega' and (text() = ' Cambiar tipo de entrega' or . = ' Cambiar tipo de entrega')]</value>
      <webElementGuid>e8c1a018-da65-49d1-b133-f5d99ddc4643</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
