<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_PAQUETE</name>
   <tag></tag>
   <elementGuidId>f2364ffb-0f90-44f3-9f80-7b936ffe1199</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonPaquete']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonPaquete</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>146b4898-217b-463a-9385-2540acd6e488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonPaquete</value>
      <webElementGuid>a5de8f15-b4f1-4022-ba29-70d95aaaf34e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonComprobante ml-15</value>
      <webElementGuid>781b4442-0501-4846-b266-0665c1b884d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>3b2ea577-cb99-4986-9eaf-1c85c1f6d0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PAQUETE</value>
      <webElementGuid>1e36c577-93d8-4712-8dde-a8381e9720d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonPaquete&quot;)</value>
      <webElementGuid>3a1a30d1-a999-47ca-b043-99a1a1cbf6a2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonPaquete']</value>
      <webElementGuid>5ca5653e-cd0e-4f43-a584-96188e487245</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[3]/button</value>
      <webElementGuid>f98cd9ba-dc03-4ea1-80db-2173ea24eb42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona el tipo de envío que deseas realizar.'])[1]/following::button[1]</value>
      <webElementGuid>26552757-3ebf-480b-9300-5b2b563f71fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué estas enviando?'])[1]/following::button[1]</value>
      <webElementGuid>60bfe0c1-b9f4-4c9f-aa04-d0bc2cba500b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOBRE'])[1]/preceding::button[1]</value>
      <webElementGuid>ccc49ef9-2841-4885-ae8d-8be74b6e7243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione un tipo de artículo'])[1]/preceding::button[2]</value>
      <webElementGuid>3d2b7467-b6a7-4ead-85f8-97ed4c2e554d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='PAQUETE']/parent::*</value>
      <webElementGuid>b6e391d5-4b69-493f-8b6e-d81356e2d371</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/button</value>
      <webElementGuid>50932611-e124-4125-bc89-89e5cb27772b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonPaquete' and (text() = 'PAQUETE' or . = 'PAQUETE')]</value>
      <webElementGuid>247b653b-31c8-4b50-b3f9-8aa4f749e8e5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
