<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_AMAZONAS - BAGUA - BAGUADESTINO</name>
   <tag></tag>
   <elementGuidId>338268ac-986b-4ff5-afd4-238cacc58acb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='seleccionaDestino']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.position-a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>3385faa2-8d98-4179-82b7-04bc279b0c30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>position-a</value>
      <webElementGuid>c1569f57-50b5-4084-8ddc-8aae6ff87b73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AMAZONAS - BAGUA - BAGUADESTINO</value>
      <webElementGuid>ee02fb51-6d63-4b43-a234-0b664feb3f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;seleccionaDestino&quot;)/div[@class=&quot;position-a&quot;]</value>
      <webElementGuid>76433d22-39d5-4f08-9e6e-874838e0f799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='seleccionaDestino']/div</value>
      <webElementGuid>9fa9ade0-534e-4903-9741-2b4baa2e015c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hacia:'])[1]/following::div[1]</value>
      <webElementGuid>b89c722e-906a-45ae-97ab-ca9a10f9fc8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ORIGEN'])[2]/following::div[2]</value>
      <webElementGuid>22f7112d-86fc-402d-bef6-d6029a0bee7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div</value>
      <webElementGuid>6f6a868e-13b8-4567-86c8-6debbb875876</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'AMAZONAS - BAGUA - BAGUADESTINO' or . = 'AMAZONAS - BAGUA - BAGUADESTINO')]</value>
      <webElementGuid>5b820394-413d-49bd-af5f-6bd445ad2d56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
