<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Destino no Permitido</name>
   <tag></tag>
   <elementGuidId>518c31ca-1e77-40d6-b807-a5ed1c854af2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h2[@id='swal2-title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#swal2-title</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
      <webElementGuid>1fa78d8f-db94-48c5-8fa8-6ab1a979c124</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>94bd2dcb-e1b8-40a8-b989-9016ad720fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>swal2-title</value>
      <webElementGuid>f5bb85e2-debf-44d0-8805-5b32c7935013</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Destino no Permitido</value>
      <webElementGuid>c0504244-85bd-4ef3-b3d6-40aa833fdcba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;swal2-title&quot;)</value>
      <webElementGuid>bb4615a3-1901-403a-a85b-ba8bf3a4ec82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//h2[@id='swal2-title']</value>
      <webElementGuid>4847f141-d5fc-456d-8fef-4f5bfb15701e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[1]/following::h2[1]</value>
      <webElementGuid>1ee929ef-18b5-4b73-bf33-57f72c317358</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'swal2-title', '&quot;', ')')])[1]/following::h2[1]</value>
      <webElementGuid>0eed1222-6881-4664-8d84-b0f62beec685</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Este destino no permite RECOJO EN TIENDA, por favor seleccione otro tipo de entrega'])[1]/preceding::h2[1]</value>
      <webElementGuid>26892333-213d-483d-9de5-510bf37b2efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[1]/preceding::h2[1]</value>
      <webElementGuid>f8ab767f-e4a7-4feb-8c8d-5a1e78cb9d99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Destino no Permitido']/parent::*</value>
      <webElementGuid>df4aa52c-c486-435b-9b5e-bfeb2795c401</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h2</value>
      <webElementGuid>a4a622c4-168a-4a53-a753-70273f2e136d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h2[@id = 'swal2-title' and (text() = 'Destino no Permitido' or . = 'Destino no Permitido')]</value>
      <webElementGuid>78f09071-01ae-4228-960f-3e29dc7338f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
