<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingresa el destino de tu envo_inputBu_d7b93a</name>
   <tag></tag>
   <elementGuidId>cc79abd8-0c4a-4abd-a643-7c595fc8d275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputBuscarOrigen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputBuscarOrigen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7d1b8777-2cdd-4b22-8a2d-d21c8d0fa331</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>6b56afc0-77af-456b-9e0e-37e5b7f25c7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputBuscarOrigen</value>
      <webElementGuid>900d43ac-ed34-4c3a-83b8-ee763e3ade20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>e9b4651a-b032-43e6-bf1e-04bff32dfef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Busca el punto de llegada</value>
      <webElementGuid>565f2aa1-0024-456c-b836-5715cf61eac8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>61a79842-255c-41db-978f-6232942f7c3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>ae303aa7-ebe0-4b80-a817-fa64b1812ce8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>3d0dfe80-81f9-45fb-8b6e-cd73d401c97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputBuscarOrigen&quot;)</value>
      <webElementGuid>af6d9a24-1296-4de1-a896-7ee7f62190b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputBuscarOrigen']</value>
      <webElementGuid>51eaeaf6-c5da-43f3-8242-319e5e93106f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-lista-ubigeo-destino/div/div/div/div[2]/div/input</value>
      <webElementGuid>dfc46293-1e47-4e67-9756-eee794edb1a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-lista-ubigeo-destino/div/div/div/div[2]/div/input</value>
      <webElementGuid>3d123c55-1fc4-4862-917d-0af2035ebb5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputBuscarOrigen' and @type = 'text' and @placeholder = 'Busca el punto de llegada']</value>
      <webElementGuid>7c0847a1-f13c-4430-bc4f-5a230edb53a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-listar-envios/div[2]/div[2]/div/div[2]/app-quien-recibe/app-lista-ubigeo-destino/div/div/div/div[2]/div/input</value>
      <webElementGuid>31f57845-d04d-4700-a136-fc6cf3dd6933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div[2]/div/input</value>
      <webElementGuid>b5d8e797-fcd2-4d38-93b2-3abf10196762</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
