<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_DIRECCIN EXACTA_inputReferenciaEDITAR</name>
   <tag></tag>
   <elementGuidId>009ff6ff-3168-4a7e-b900-000aac6f705c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;inputReferenciaDestinoComp&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputReferenciaDestino</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>24e67af8-4f4d-45fb-aef5-5c27bd59cfc0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d67d6638-b7c4-406a-9d32-ac903fbc8d1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d3ef4937-8c87-4490-a6f8-fec79de71368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputReferenciaDestino</value>
      <webElementGuid>fdcdb384-db58-4055-ac36-bb898be271ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputReferenciaDestino</value>
      <webElementGuid>c77285c5-2f68-49ca-9c5e-d303e8485465</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>b56b5c4a-1afb-476c-9f99-9e92a3c672d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d5d21a65-534b-4360-bf13-e1de83639d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputReferenciaDestino</value>
      <webElementGuid>355318b5-da7a-4d99-9f41-b2038da60e28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputReferenciaDestino&quot;)</value>
      <webElementGuid>58111ec6-69b2-40eb-a543-ed820b47f25b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputReferenciaDestino']</value>
      <webElementGuid>d24cb7b5-25c2-4297-a6e6-1bd43c84e307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[3]/div[3]/div/div[3]/input</value>
      <webElementGuid>50ce8a59-460e-4791-85b3-4ee647b35c84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/input</value>
      <webElementGuid>845d30c5-0633-46c1-87d8-061110ac7af7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputReferenciaDestino']</value>
      <webElementGuid>e47d4d65-9288-485f-98c1-2670f3966f82</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
