<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TIPO DE DOCUMENTO  DNI  CE</name>
   <tag></tag>
   <elementGuidId>be9f5ef5-fad7-496e-bb06-dbeb234ea63d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tipoDocumento</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoDocumento']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5dc28bb6-7c75-4d36-a33b-6fec76d5a9be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoDocumento</value>
      <webElementGuid>ce8edbf4-1505-464d-9970-357c5cf796d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>tipoDocumento</value>
      <webElementGuid>c9b083b6-cfc1-48d1-86d4-87c574809a55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>tipoDocumento</value>
      <webElementGuid>66bd4a4d-9d5f-42d8-a9b6-f88e679ed301</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-model</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e7f3c83c-c136-4a56-bdb6-5e2f74851ccc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7cc4e0ee-2cb9-4e57-b7f6-88a3191e1b67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>233076ba-16d0-48d7-807e-68354627dec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> TIPO DE DOCUMENTO  DNI  CE </value>
      <webElementGuid>8e3b8266-f64a-4f0f-8e5e-27b28d92fd19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoDocumento&quot;)</value>
      <webElementGuid>464a7b31-09b6-4250-828b-7eb351c1881d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoDocumento']</value>
      <webElementGuid>17cc939f-3076-4301-a201-1b5db747b349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[4]/div/select</value>
      <webElementGuid>6862a0a3-9abf-4cc3-aea0-f65914bd59d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FACTURA'])[1]/following::select[1]</value>
      <webElementGuid>8d09f276-5861-430d-b32b-8d5b1294b373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='BOLETA'])[1]/following::select[1]</value>
      <webElementGuid>0af263cf-48dc-464e-bb8c-29f4dbb08f1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NÚMERO DOCUMENTO'])[1]/preceding::select[1]</value>
      <webElementGuid>0dd14789-7e53-4bd2-b0f5-f1c0799016ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NOMBRES Y APELLIDOS'])[1]/preceding::select[1]</value>
      <webElementGuid>37cea1fe-65a3-4cd0-841d-bc0ab5d9f93a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>76f37f41-0e3a-487f-af32-fefd68b25360</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoDocumento' and (text() = ' TIPO DE DOCUMENTO  DNI  CE ' or . = ' TIPO DE DOCUMENTO  DNI  CE ')]</value>
      <webElementGuid>bd889312-5307-40b9-b2a8-e6f8b74f5657</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
