<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Cancelar</name>
   <tag></tag>
   <elementGuidId>a0c543a2-1b40-4843-b846-79d3b2d02d0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>small.span-cancel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cancelarValidacionApellido']/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>cd887b5e-4fca-48a7-bd81-8680d340f281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span-cancel</value>
      <webElementGuid>622aaff6-8462-4f15-8a4a-d7b3966c1888</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Cancelar</value>
      <webElementGuid>dc1eafff-1f24-4589-b3fa-a71b2b444fd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cancelarValidacionApellido&quot;)/small[@class=&quot;span-cancel&quot;]</value>
      <webElementGuid>eba595c0-0e26-469e-933b-15e9a48f6fc0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cancelarValidacionApellido']/small</value>
      <webElementGuid>7fcd08fe-aac5-49ab-b460-97bbcc16a362</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APELLIDO PATERNO'])[1]/following::small[1]</value>
      <webElementGuid>34e7dd48-aa5c-4581-93c3-d512610704e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Escriba su primer apellido igual al del documento de identidad'])[1]/following::small[1]</value>
      <webElementGuid>f006319a-9380-4a33-95ce-97f2b516a51d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::small[1]</value>
      <webElementGuid>d05cbaae-141d-4aae-8187-826c095d71b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Cancelar']/parent::*</value>
      <webElementGuid>d9f0557c-9725-4e96-ae03-de0cb4f702f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-validacion-apellido-modal/div/div/div[3]/div/small</value>
      <webElementGuid>274138e8-aefb-4963-bcfd-a2c28da41ee9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Cancelar' or . = 'Cancelar')]</value>
      <webElementGuid>b68796f6-9547-43c5-acd5-0e68f209fc44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
