<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Escriba su primer apellido igual al d_19137b</name>
   <tag></tag>
   <elementGuidId>2854f34c-29a3-4709-a082-82c2a206770d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputConfirmApellido']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputConfirmApellido</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9580a89f-176d-4031-8c0b-5badfea83065</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>23f77ec4-35eb-4586-b4e3-3471ce554f5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputConfirmApellido</value>
      <webElementGuid>a83d3156-d10f-4b8d-b428-c52af1adf32f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-pristine ng-valid ng-touched</value>
      <webElementGuid>b5f410d8-52fe-4ef1-b2bb-bcf661e8fcf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputConfirmApellido&quot;)</value>
      <webElementGuid>8b56402b-814b-485c-95da-dc5c39232009</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>293fded7-75d3-4026-8f41-93db06ddcfea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputConfirmApellido']</value>
      <webElementGuid>92ead237-2a34-48fe-9661-5913588f8e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-validacion-apellido-modal/div/div/div[2]/div/input</value>
      <webElementGuid>41d2bec8-189a-43e8-91d8-ce60374493e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-validacion-apellido-modal/div/div/div[2]/div/input</value>
      <webElementGuid>9effc5cb-9097-4570-b503-59b70b858f7e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputConfirmApellido']</value>
      <webElementGuid>549d717e-d65a-48ce-8d34-af1ed109891b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
