<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SOBRE</name>
   <tag></tag>
   <elementGuidId>9c87e2dd-e0b7-48b7-8af2-1093898202c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#buttonSobre</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='buttonSobre']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a4ce0ab5-8c46-48c0-ad26-876edef30590</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonSobre</value>
      <webElementGuid>ca3a3662-106b-48a9-a686-0cbd090dd151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonComprobante ml-15</value>
      <webElementGuid>a8284368-5ca6-471f-85b3-382d9abc1660</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>baf45373-c9a3-4a27-a11b-2f6e51c5d508</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SOBRE</value>
      <webElementGuid>ba2260d9-425a-4112-a9c9-4e15bd72816a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonSobre&quot;)</value>
      <webElementGuid>78c819f2-a23d-4365-890e-befdaa417ae9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='buttonSobre']</value>
      <webElementGuid>11f59ce2-b2dd-4023-9b2b-b645b97352c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[3]/button[2]</value>
      <webElementGuid>145d1d4a-63f6-483a-927c-cb35bdcb122e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='PAQUETE'])[1]/following::button[1]</value>
      <webElementGuid>5af88cc1-acfa-45fe-8b1b-7312e5678372</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Selecciona el tipo de envío que deseas realizar.'])[1]/following::button[2]</value>
      <webElementGuid>6906ebc4-343e-427b-9072-ce1eea5d2b96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione un tipo de artículo'])[1]/preceding::button[1]</value>
      <webElementGuid>44ed8d7c-fc76-435c-a086-eaff9dcba43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALOR DEL CONTENIDO'])[1]/preceding::button[1]</value>
      <webElementGuid>9ce42ac1-c12b-4de6-aa29-573cd5b75efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='SOBRE']/parent::*</value>
      <webElementGuid>79ed7a14-424f-49c0-9537-7a370b6a9125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]</value>
      <webElementGuid>691f1bc9-e9cf-4a8c-bd5d-15a7db5df0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'buttonSobre' and (text() = 'SOBRE' or . = 'SOBRE')]</value>
      <webElementGuid>4e4f062b-e2d6-4487-a754-6a17ab925d12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
