<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_REGISTRAR NUEVO ENVO</name>
   <tag></tag>
   <elementGuidId>ee822080-3527-4cbd-bd5f-63de97f518bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;content&quot;]/main/app-pago-exitoso-pe/div[2]/div[7]/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mt-5 > button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6483d7dd-75fa-4b8f-b34e-e3eb6396fbfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REGISTRAR NUEVO ENVÍO</value>
      <webElementGuid>409212f8-b64d-4c29-8581-8a4483ae759f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;content&quot;)/main[1]/app-pago-respuesta[1]/div[@class=&quot;shadow border-card contenedor-div border-respuesta-responsive&quot;]/div[@class=&quot;mt-5&quot;]/button[1]</value>
      <webElementGuid>a6394469-ccfa-49a4-9e00-4fc91c8bfc85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-pago-respuesta/div[2]/div[7]/button</value>
      <webElementGuid>48fc3194-87f1-4e7c-9769-9a2f098c5e8b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recuerda rotular correctamente tus envíos'])[1]/following::button[1]</value>
      <webElementGuid>dd7230a1-1c83-4363-8260-20f68001d809</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ver tiendas/agentes'])[1]/following::button[1]</value>
      <webElementGuid>a13d3ea7-79a4-4da4-a973-daa41f7e1daf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='REGISTRAR NUEVO ENVÍO']/parent::*</value>
      <webElementGuid>70f6ed81-8cf9-4d2f-8587-137a9cefd9e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button</value>
      <webElementGuid>e80289d1-1388-40ff-adfd-c10a7f288b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'REGISTRAR NUEVO ENVÍO' or . = 'REGISTRAR NUEVO ENVÍO')]</value>
      <webElementGuid>b4a59189-37b4-41f6-a4f6-67c1bc6206f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-pago-exitoso-pe/div[2]/div[7]/button</value>
      <webElementGuid>8f8b1c06-1a45-4a12-9381-80d8a52e789e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
