<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>CONTINUAR_listEnvios</name>
   <tag></tag>
   <elementGuidId>0576f4cf-0c4b-468b-a3ef-138d0ca0de0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;avanzarListarEnvios&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#avanzarQueEnvias > img.btn-icon</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>d2fa968c-d02a-4637-8de2-94179ccadbb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>assets/images/icon_arrow_right.png</value>
      <webElementGuid>93118ea8-8e03-4d19-8feb-c794e59a79ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>f9fbdd7d-b40d-4add-8bee-58f2f94e54c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>2d8fa606-a8f3-4f1f-8442-39b86003df34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-icon</value>
      <webElementGuid>70c03a22-4f1a-4ee5-9c96-9b4757d19c6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avanzarQueEnvias&quot;)/img[@class=&quot;btn-icon&quot;]</value>
      <webElementGuid>2f4dbf2d-9aa6-401a-b6b1-90bad51aff85</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='avanzarQueEnvias']/img</value>
      <webElementGuid>bd5d41ee-eadb-494c-a11b-eb0ac9a78e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/button[2]/img</value>
      <webElementGuid>a08c0850-b8ec-48b4-9790-450402d1f502</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'assets/images/icon_arrow_right.png']</value>
      <webElementGuid>fcee6e44-7aa9-4f14-a1ea-056863812d38</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
