<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Clcula el peso de tu envo ingresando _53efce</name>
   <tag></tag>
   <elementGuidId>5c01ceed-8dcf-4aa2-9a8c-ae4d4d5e938c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#inputAncho</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputAncho']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b65b6cf9-fa46-4420-b24d-e0c49047712a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>122c1c97-0ca8-4a81-8e4f-32cd44649b2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>614ff191-d110-4dc7-8037-d0e53da1d6e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputAncho</value>
      <webElementGuid>1f086040-0431-4658-95f0-e18c3c2286c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>inputAncho</value>
      <webElementGuid>1abd738e-4f38-4de3-8f5f-8fd3f2762814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-pristine ng-invalid ng-touched</value>
      <webElementGuid>56338db0-19e2-4d5b-ae11-3a8effd41818</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-maxlength</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>5783d2fd-4443-419e-9344-870f83330a8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ng-reflect-name</name>
      <type>Main</type>
      <value>inputAncho</value>
      <webElementGuid>286f745e-e66b-44f0-a699-f0fa0705c67f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputAncho&quot;)</value>
      <webElementGuid>edb97e7e-2b38-48cd-a9dd-11acdee59cad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputAncho']</value>
      <webElementGuid>f586c76d-d539-4251-8253-3173e967bbd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-ingresar-dimensiones-modal/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>e2e23756-b415-4d8e-8cd0-1cf42d8c5317</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>64208ee4-2a9c-40b9-8ab0-7c7299b43a7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'inputAncho']</value>
      <webElementGuid>b6cc6802-9956-45e1-9ebc-135b8978d583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
