<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Ejem</name>
   <tag></tag>
   <elementGuidId>19ed3a15-fd33-4abc-9a60-92f599871948</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>small.font-9.small-back-yellow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='contenedorSobreEnvio']/div[2]/small</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>17d051a6-bd65-4de3-9cf2-84c90e7f702d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>font-9 small-back-yellow</value>
      <webElementGuid>6ecc32c3-9d20-404f-aafd-a96c6fe5b317</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ejem</value>
      <webElementGuid>cb5c791b-a449-4c90-bb8a-83fbd10af5b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contenedorSobreEnvio&quot;)/div[@class=&quot;extra-info&quot;]/small[@class=&quot;font-9 small-back-yellow&quot;]</value>
      <webElementGuid>29ba636d-4e95-4df9-852e-4b9c49877d2f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='contenedorSobreEnvio']/div[2]/small</value>
      <webElementGuid>41724700-0432-4c1e-bba5-5f74981f8ea3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kg'])[1]/following::small[1]</value>
      <webElementGuid>0c41fc40-d3fb-44be-bbaf-b40771dfe7a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contrato, certificados, impresiones, etc.'])[1]/preceding::small[1]</value>
      <webElementGuid>93a07d4d-7991-4697-8ae9-a2b6d9109d03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ejem']/parent::*</value>
      <webElementGuid>3d4da4a9-0e1d-4c1c-a15a-3cac9779c28e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/small</value>
      <webElementGuid>cfdb6f9d-0c3a-4375-bc06-c394b2a2dc4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Ejem' or . = 'Ejem')]</value>
      <webElementGuid>a14b59e3-7857-4adc-9826-c91adc90ca3d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='pesoCuatroKilos']/div[2]/div/div/small</value>
      <webElementGuid>f7e6598f-dd82-4a80-b33c-0fc32ac8c689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kg'])[4]/following::small[1]</value>
      <webElementGuid>08e2a48c-e999-4f0d-be49-9036a1f7fa49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Peluches, almohadas,'])[1]/preceding::small[1]</value>
      <webElementGuid>8e768fd4-9ba2-4ff9-9086-ea3a825e2659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='lámparas, etc'])[1]/preceding::small[2]</value>
      <webElementGuid>3490f445-7f64-4b51-a251-d59915b899f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/small</value>
      <webElementGuid>8364ef87-4132-4690-a72f-46ead6c18a84</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
