<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_CONTINUAR_1_2_3_4_5</name>
   <tag></tag>
   <elementGuidId>45076ed7-0e4d-42ef-80f2-6117afbb2811</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#avanzarQuienRecibe</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='avanzarQuienRecibe']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7d17b3b3-5191-4788-9d21-3453c47a5a5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>avanzarQuienRecibe</value>
      <webElementGuid>b248123f-7dec-4762-98af-0b5fe4b919bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>boton px-3 custom-btn</value>
      <webElementGuid>4f60d1dc-005a-4c6e-a084-576178fc9695</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>42a29b3a-a8d1-416f-bf69-0b37f01e4996</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>CONTINUAR</value>
      <webElementGuid>54ff483f-68ed-43b3-a290-cf7ef59521d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;avanzarQuienRecibe&quot;)</value>
      <webElementGuid>a448d7b4-f7cb-40ad-8fe1-46ce57195044</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='avanzarQuienRecibe']</value>
      <webElementGuid>6e6a28c3-d014-47b4-be22-2c3e6c2f67e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div[2]/div/div/div[7]/button[2]</value>
      <webElementGuid>24e7e229-2dfe-4987-8f3f-69fade582796</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VOLVER'])[2]/following::button[1]</value>
      <webElementGuid>d642d08f-d268-4b73-a5ec-1a4db662f129</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Se aplica peso volumen en caso los paquetes tengan mayor tamaño que peso.'])[1]/following::button[2]</value>
      <webElementGuid>0eb90daa-7504-48e0-96a1-285000db4e0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'avanzarQuienRecibe', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>c07c741e-9578-47b7-abd3-2f24a0668cd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/button[2]</value>
      <webElementGuid>c64cb82c-4a53-4abe-bac1-d38b009e531f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'avanzarQuienRecibe' and (text() = 'CONTINUAR' or . = 'CONTINUAR')]</value>
      <webElementGuid>6c28eedd-9854-4e72-81ef-f0c0f3e947fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
