<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Continuar (1)</name>
   <tag></tag>
   <elementGuidId>58b7bd75-a047-425a-a8f9-168cf45f9987</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#payment-continue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='payment-continue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ce6909f8-51e9-436e-b136-916413718faf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>payment-continue</value>
      <webElementGuid>ff0c0bfd-7392-4430-a438-9e2162aa83fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-control btn btn-submit btn-success btn-block j-secure-form-payment-method btn-pay btn-decorator</value>
      <webElementGuid>4f423931-9b9b-42d3-adc5-83640efbda34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a52098a4-8b8d-419f-885f-0e2590422056</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continuar</value>
      <webElementGuid>ff69f9d8-14fa-4438-9606-a8c819a10c17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;payment-continue&quot;)</value>
      <webElementGuid>40325164-a24f-4abc-a0f7-a76535bb9a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/positivas/CargoAdjunto/iframe_Cancel_visaNetJS</value>
      <webElementGuid>10d98ad8-fc9d-4cb6-83c8-a5cb2dfbda2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='payment-continue']</value>
      <webElementGuid>af9d02b6-e0dc-4b33-b564-43d25e7f321b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethods']/div/div/section/button</value>
      <webElementGuid>c2eed4f9-265b-457d-96ca-76231cff2a71</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago con Yape'])[1]/following::button[1]</value>
      <webElementGuid>1de218b9-2473-4b7c-808d-2966b26ada56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pago con Puntos/Millas'])[1]/following::button[1]</value>
      <webElementGuid>c6440201-294a-47ae-b113-0e38bf615519</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Cómo realizar tu compra con PagoEfectivo?'])[1]/preceding::button[1]</value>
      <webElementGuid>dcc24175-c616-40c6-bd05-28f6b58c63e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='✓ Depósitos en efectivo vía PagoEfectivo'])[1]/preceding::button[1]</value>
      <webElementGuid>2e061501-4823-439d-b858-345756137f6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Continuar']/parent::*</value>
      <webElementGuid>c605d27c-3b4e-4e40-a7ec-fed5d4be18ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>f9f7ecdd-1adf-4867-93dd-41cb578fc658</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'payment-continue' and @type = 'button' and (text() = 'Continuar' or . = 'Continuar')]</value>
      <webElementGuid>bd382a89-06ac-460c-b704-007bd237117b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
