<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_BOLETA</name>
   <tag></tag>
   <elementGuidId>910e122e-8c28-4172-90d8-ed76c71dba10</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='opcionBoleta']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#opcionBoleta</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c392d6ff-8230-4893-aae9-492c775c7c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>opcionBoleta</value>
      <webElementGuid>dfd4df06-1b26-4475-b97e-f6b576545dd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>buttonComprobante ml-15</value>
      <webElementGuid>7ea0c303-9977-40b0-861f-69d02affb275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>33f977d4-1fb7-4edf-b27a-af643226f8c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>BOLETA</value>
      <webElementGuid>a8b960dd-46ea-4407-a866-0a3d1aecdb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opcionBoleta&quot;)</value>
      <webElementGuid>363b98a7-26c0-4e11-9700-993cc4c762ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='opcionBoleta']</value>
      <webElementGuid>ab3874a4-e20a-4d38-9ed0-c3e5acd93acc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[3]/div/div/button</value>
      <webElementGuid>d0bd3688-cd0d-4ce6-ba69-e028e1af6afe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tipo comprobante:'])[1]/following::button[1]</value>
      <webElementGuid>c11bf1d1-ebc8-4496-9225-ec2ba116fffb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Completa los datos de la persona que realiza el envío.'])[1]/following::button[1]</value>
      <webElementGuid>e74da060-9eae-4b97-a584-e98eb71a8c9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FACTURA'])[1]/preceding::button[1]</value>
      <webElementGuid>8253786d-b856-4855-b525-2324839ddab7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NÚMERO DOCUMENTO'])[1]/preceding::button[2]</value>
      <webElementGuid>311cfcf8-c8d0-49ea-ae64-320485bc5ab4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='BOLETA']/parent::*</value>
      <webElementGuid>83e52191-0e46-470d-af99-0727a112e2f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/button</value>
      <webElementGuid>781c3974-afb6-4c16-b99f-3c919adf3c31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'opcionBoleta' and (text() = 'BOLETA' or . = 'BOLETA')]</value>
      <webElementGuid>deda1863-f736-4776-8c4f-bed320eea401</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
