<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_REALIZAR UN ENVO</name>
   <tag></tag>
   <elementGuidId>6b78c528-d417-49ba-a026-45bfbdd69ab3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='buttonEnvio']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#buttonEnvio</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9db042b4-685f-4b48-addd-b67058df8b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>buttonEnvio</value>
      <webElementGuid>f8078714-2246-41ea-bf84-951c98b14d86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>option-card px-4 pb-3 ptc-4 text-center border rounded-10 shadow-sm back-color-orange</value>
      <webElementGuid>545f2f49-7d03-4d93-bc3b-87cd00c654d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>REALIZAR UN ENVÍO</value>
      <webElementGuid>fa3cb2eb-ff44-4f32-9afb-60eb02f9f77e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;buttonEnvio&quot;)</value>
      <webElementGuid>27cc06ed-2a04-498e-943d-33706e20a866</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='buttonEnvio']</value>
      <webElementGuid>55fdd330-4cae-4a5f-af8e-d64f91014068</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-principal/div/div[2]/div/div/div</value>
      <webElementGuid>c79cf800-e2c1-4fee-9784-677b81a61875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Qué deseas realizar hoy?'])[1]/following::div[3]</value>
      <webElementGuid>b9c1994b-2655-4802-82aa-abde34ea16d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div</value>
      <webElementGuid>30a911f1-0477-4313-8da2-c4a1f68b949d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'buttonEnvio' and (text() = 'REALIZAR UN ENVÍO' or . = 'REALIZAR UN ENVÍO')]</value>
      <webElementGuid>25eb4626-b44f-4853-89fa-d1955c6683f9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
