<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i</name>
   <tag></tag>
   <elementGuidId>f2853895-b332-4c44-a6b6-f7333ef9ad25</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;paymentMethods&quot;]/div/div/section/label[1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.radio.state-success > i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>f1cd6701-af3a-4f06-980c-e60b06fa8435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;paymentMethods&quot;)/div[@class=&quot;form-group row&quot;]/div[@class=&quot;col col-11&quot;]/section[1]/label[@class=&quot;radio state-success&quot;]/i[1]</value>
      <webElementGuid>0bd0092d-c2cb-4877-a6be-115370a48069</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/positivas/CargoAdjunto/iframe_Cancel_visaNetJS</value>
      <webElementGuid>4e0233cd-fafc-412e-9881-2d10c60e1420</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='paymentMethods']/div/div/section/label/i</value>
      <webElementGuid>9880d6f4-3b93-4e88-9103-344ff5ae57b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/div/section/label/i</value>
      <webElementGuid>62295458-d594-4981-ab13-b77c5758ef6d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
