<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Ingresa el destino de tu envo_inputBu_d7b93a</name>
   <tag></tag>
   <elementGuidId>535ba928-6196-4fd6-adf0-d8f12e56835a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inputBuscarOrigen']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#inputBuscarOrigen</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f2fa1561-1d74-47ae-b4e5-31f3d8ca9e8e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>0aa646aa-16de-4480-ada2-3d6b559fb194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>inputBuscarOrigen</value>
      <webElementGuid>543213ae-90d1-421b-acdc-73e00806ad01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0d13f6a-0882-4f68-920a-76be2415894a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Busca el punto de llegada</value>
      <webElementGuid>23da62ec-0445-4285-ae9e-ce10c9135bdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>33b9c101-cc41-4314-8ea6-46e01292d92e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>d8e4cd99-7e9f-4c5e-9b93-ed4b7db5ee15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inputBuscarOrigen&quot;)</value>
      <webElementGuid>d67fb5a0-c14e-4c66-bcb7-8bd1e69ef86d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='inputBuscarOrigen']</value>
      <webElementGuid>8c125ff5-f8be-4be4-9f35-a7a4b66a736e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-lista-ubigeo-destino/div/div/div/div[2]/div/input</value>
      <webElementGuid>763e645e-8114-49a6-9d28-7fb717d39b59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-lista-ubigeo-destino/div/div/div/div[2]/div/input</value>
      <webElementGuid>da331b18-e8ff-42b0-89a7-3e2592b637e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'inputBuscarOrigen' and @type = 'text' and @placeholder = 'Busca el punto de llegada']</value>
      <webElementGuid>28e3e60c-b205-452e-a05a-698ed47ecba0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
