<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_compras por internet_number</name>
   <tag></tag>
   <elementGuidId>2c0eacaf-5a94-4c58-bdab-4c8a6ee66e2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#number</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='number']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e1b1a37a-963f-47b1-86da-573565e587a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>13a0b89b-a6c7-4319-9437-404a55c667a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c2e1e76a-43fc-443f-af68-063cd7a85f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>1bbb5a0f-aa6e-4745-b9f6-7dd4ed3f05c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c2e11b01-1ed0-42a1-a870-b96e96aeb334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Número de Tarjeta</value>
      <webElementGuid>eca1409c-cde9-47ee-92f2-12db1a512469</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>identified</value>
      <webElementGuid>41ed0113-e992-46b0-bf17-8c427ef2b7f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;number&quot;)</value>
      <webElementGuid>aa3f7dc2-79fc-447a-9055-9034d84f1d06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/positivas/CargoAdjunto/iframe_Cancel_visaNetJS</value>
      <webElementGuid>a5937860-1472-4420-8915-9e5cee1be489</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='number']</value>
      <webElementGuid>5cef286a-1eb2-4257-ae54-e42c0c216e4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='default']/div[3]/div/section/label/input</value>
      <webElementGuid>424d0f4d-8b98-4c5c-8075-13b3efb463b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/section/label/input</value>
      <webElementGuid>e3d49a23-42b4-45f3-88f7-287549ec5b32</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel' and @name = 'number' and @id = 'number' and @placeholder = 'Número de Tarjeta']</value>
      <webElementGuid>01cd15b7-556a-4335-ae83-9f2eb0c9dd02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
