<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Impresoras, laptops, consolas, etc_se_20c89d</name>
   <tag></tag>
   <elementGuidId>5b1d8723-4e9d-4ad0-b92c-efd3eaf9c8ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='selectDestinoTienda']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#selectDestinoTienda</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3776cc9e-fc15-42d2-8073-39cb6d57d534</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>95ca1ceb-fe5c-4527-958c-7ea0d25afd70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>3a6f1cb1-d2ac-49b4-aab5-28a10c452e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectDestinoTienda</value>
      <webElementGuid>6ea3fc11-5158-444e-9b03-15b4116f5057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>selectDestinoTienda</value>
      <webElementGuid>ed1bc542-1000-4394-ada0-845ea0389a7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material ng-untouched ng-pristine ng-invalid</value>
      <webElementGuid>8f1b9cf5-fdff-4084-8e47-a32c5db56506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectDestinoTienda&quot;)</value>
      <webElementGuid>37333ddc-1f43-407c-ab0f-daf97b6d7ceb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='selectDestinoTienda']</value>
      <webElementGuid>1db56741-96ea-41be-bf4b-92642428f870</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div/div/input</value>
      <webElementGuid>eb79a2c7-a46a-42be-890d-0713228fc138</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-cargo-adjunto/div/div/div[5]/div/div/input</value>
      <webElementGuid>2f2eac65-a75d-4368-a06e-12775186c893</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'selectDestinoTienda']</value>
      <webElementGuid>5b866bcd-7045-4bf9-a4f7-0f4504330020</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
