<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SELECCIONE TIENDA ATE - AV JAVIER PR_1a42df</name>
   <tag></tag>
   <elementGuidId>70e56d08-0f8d-4755-9a56-ba830ad668af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#selectOficinasRetornoCargo</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='selectOficinasRetornoCargo']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a404d943-8cdb-42f8-bbc3-aadd09a1caff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>8959ec89-cd70-4357-8143-36e9f0d67a6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>selectOficinasRetornoCargo</value>
      <webElementGuid>d72b962f-688b-4feb-b974-b5ff2ef3bfca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ng-untouched ng-pristine ng-valid</value>
      <webElementGuid>cb389802-5ad3-413e-8b65-9409552ba95b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SELECCIONE TIENDA ATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO   ATE - AV CARRETERA CENTRAL 7.5 KM S/N   ATE - CA 1 DE MAYO MZ 11 LTE 10 URB SAN GREGORIO   ATE - AV LA ESTRELLA S/N URB SANTA CLARA ((CENTRO COMERCIAL REAL PLAZA ) AL FRENTE DE TAI LOY)  ATE - AV LOS QUECHUAS S/N URBANIZACION SALAMANCA   ATE - Avenida Nicolás Ayllón, Ate, Perú(AV. CARRETERA CENTRAL 14.8 KM. GLORIA GRANDE LIMA - LIMA - ATE)  ATE - AV LOS QUECHUAS NRO 1485 URB SALAMANCA  </value>
      <webElementGuid>4692599d-efba-4839-8584-4be1bc39b4ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;selectOficinasRetornoCargo&quot;)</value>
      <webElementGuid>441811b3-bd8a-4cd5-9737-bfe7b22909af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='selectOficinasRetornoCargo']</value>
      <webElementGuid>b3d0d879-5f9e-4feb-b28a-a9eac6a25859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div/div[2]/select</value>
      <webElementGuid>8bfc0eb6-395b-45f4-a3ab-dbab5d9f8a3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESE EL DESTINO DEL CARGO'])[1]/following::select[1]</value>
      <webElementGuid>5f530a4c-16c3-4521-b0a7-1a011083a31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Impresoras, laptops, consolas, etc'])[2]/following::select[1]</value>
      <webElementGuid>5e4d7041-3a96-4411-942d-14213bfb925a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/preceding::select[1]</value>
      <webElementGuid>2b1c0853-b8a9-4c95-b5a4-ab6207f7ed6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Aceptar'])[1]/preceding::select[1]</value>
      <webElementGuid>468b6128-680c-4357-a4cf-0db17d2005ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div[2]/select</value>
      <webElementGuid>b99edb44-9686-4abc-83f2-b385ae7b8141</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'selectOficinasRetornoCargo' and (text() = 'SELECCIONE TIENDA ATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO   ATE - AV CARRETERA CENTRAL 7.5 KM S/N   ATE - CA 1 DE MAYO MZ 11 LTE 10 URB SAN GREGORIO   ATE - AV LA ESTRELLA S/N URB SANTA CLARA ((CENTRO COMERCIAL REAL PLAZA ) AL FRENTE DE TAI LOY)  ATE - AV LOS QUECHUAS S/N URBANIZACION SALAMANCA   ATE - Avenida Nicolás Ayllón, Ate, Perú(AV. CARRETERA CENTRAL 14.8 KM. GLORIA GRANDE LIMA - LIMA - ATE)  ATE - AV LOS QUECHUAS NRO 1485 URB SALAMANCA  ' or . = 'SELECCIONE TIENDA ATE - AV JAVIER PRADO ESTE NRO 8680 URBANIZACION URB MAYORAZGO   ATE - AV CARRETERA CENTRAL 7.5 KM S/N   ATE - CA 1 DE MAYO MZ 11 LTE 10 URB SAN GREGORIO   ATE - AV LA ESTRELLA S/N URB SANTA CLARA ((CENTRO COMERCIAL REAL PLAZA ) AL FRENTE DE TAI LOY)  ATE - AV LOS QUECHUAS S/N URBANIZACION SALAMANCA   ATE - Avenida Nicolás Ayllón, Ate, Perú(AV. CARRETERA CENTRAL 14.8 KM. GLORIA GRANDE LIMA - LIMA - ATE)  ATE - AV LOS QUECHUAS NRO 1485 URB SALAMANCA  ')]</value>
      <webElementGuid>9757bd84-0d1a-410f-90e8-62b601658742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
