<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_TIPO DE ARTCULO  ACCESORIOS Y EQUIPO_f94c1d</name>
   <tag></tag>
   <elementGuidId>312e1a30-ad9a-4033-a12e-2c127ff31899</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='tipoArticulo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#tipoArticulo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>30a1dada-7b7d-4187-907f-273d2eb92b54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tipoArticulo</value>
      <webElementGuid>ef4ef702-8730-47cf-babc-3a03614610d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>formcontrolname</name>
      <type>Main</type>
      <value>tipoArticulo</value>
      <webElementGuid>4093bddf-040b-45f4-b2d4-922df95a4c37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>max-size ng-valid ng-dirty ng-untouched</value>
      <webElementGuid>92c25aee-5eea-443e-ad69-306af1936319</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>439bf643-5756-4ebe-9afd-0fc1b0e66f60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> TIPO DE ARTÍCULO  ACCESORIOS Y EQUIPOS ELECTRONICOS  ACCESORIOS PARA FIESTAS  ARTÍCULOS DE LIMPIEZA  ARTÍCULOS PUBLICITARIOS  BISUTERIA  CAJA  TARJETAS PERSONALES  MUEBLES Y DECOHOGAR  FERRETERÍA Y CONSTRUCCIÓN  ALIMENTACION Y BEBIDAS  COSMETICOS  ELECTROHOGAR  JUGUETES  MATERIAL MEDICO  MEDICINAS  REPUESTOS  ROPA Y ACCESORIOS  VALIJA-DOCUMENTOS  UTILES DE ESCRITORIO  UTILES DE OFICINA </value>
      <webElementGuid>e0eb671f-fffc-4acc-809c-d43889258062</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tipoArticulo&quot;)</value>
      <webElementGuid>2df717ed-03e5-47b9-abcc-719bcffb2e05</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='tipoArticulo']</value>
      <webElementGuid>d2f9dffb-b5b4-437e-89cd-9a6832b1c3f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/div[2]/div/div/div/div[5]/div/select</value>
      <webElementGuid>7f6b372c-f45e-44b4-99f6-75ee574f6612</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Seleccione un tipo de artículo'])[1]/following::select[1]</value>
      <webElementGuid>10aec96e-9e7f-47a6-9126-22ef92f34bdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SOBRE'])[1]/following::select[1]</value>
      <webElementGuid>b66fec72-ee1c-4e0a-8eee-2c2a4199ebb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='VALOR DEL CONTENIDO'])[1]/preceding::select[1]</value>
      <webElementGuid>3c00be50-aa5c-4270-a9fb-2624cbf756d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ESPECIFICAR ARTÍCULO'])[1]/preceding::select[1]</value>
      <webElementGuid>7830116c-de45-462d-9196-ba0be9385d48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>6d8a6a0d-d203-463c-88f8-d6a66200cdc0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'tipoArticulo' and (text() = ' TIPO DE ARTÍCULO  ACCESORIOS Y EQUIPOS ELECTRONICOS  ACCESORIOS PARA FIESTAS  ARTÍCULOS DE LIMPIEZA  ARTÍCULOS PUBLICITARIOS  BISUTERIA  CAJA  TARJETAS PERSONALES  MUEBLES Y DECOHOGAR  FERRETERÍA Y CONSTRUCCIÓN  ALIMENTACION Y BEBIDAS  COSMETICOS  ELECTROHOGAR  JUGUETES  MATERIAL MEDICO  MEDICINAS  REPUESTOS  ROPA Y ACCESORIOS  VALIJA-DOCUMENTOS  UTILES DE ESCRITORIO  UTILES DE OFICINA ' or . = ' TIPO DE ARTÍCULO  ACCESORIOS Y EQUIPOS ELECTRONICOS  ACCESORIOS PARA FIESTAS  ARTÍCULOS DE LIMPIEZA  ARTÍCULOS PUBLICITARIOS  BISUTERIA  CAJA  TARJETAS PERSONALES  MUEBLES Y DECOHOGAR  FERRETERÍA Y CONSTRUCCIÓN  ALIMENTACION Y BEBIDAS  COSMETICOS  ELECTROHOGAR  JUGUETES  MATERIAL MEDICO  MEDICINAS  REPUESTOS  ROPA Y ACCESORIOS  VALIJA-DOCUMENTOS  UTILES DE ESCRITORIO  UTILES DE OFICINA ')]</value>
      <webElementGuid>0a5a01c4-4d9c-4070-bdf2-6e459c3810b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
