<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>small_Aceptar</name>
   <tag></tag>
   <elementGuidId>6361065f-6eb7-460a-bf5a-66086b6ff180</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;aceptarCargoAdjunto&quot;]
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>small.span-accept</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>small</value>
      <webElementGuid>7e7be9df-6a3b-4d7b-807a-54d3e9bb95f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>aceptarCargoAdjunto</value>
      <webElementGuid>2cfd8e27-01f7-4680-b2bb-a4394f1aa1e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>span-accept</value>
      <webElementGuid>68f2f344-d6d9-473d-821c-fb1e5c49670c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aceptar</value>
      <webElementGuid>36f742cc-c8ce-4e7e-ab97-1f57f2f734a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aceptarValidacionApellido&quot;)/small[@class=&quot;span-accept&quot;]</value>
      <webElementGuid>98fd4cd8-45e3-4e06-98d2-74ecb6187364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='aceptarValidacionApellido']/small</value>
      <webElementGuid>45025bf5-3de3-40df-8eee-76f5bf7cfc2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancelar'])[1]/following::small[1]</value>
      <webElementGuid>f4692f27-fc2b-4819-bae8-1ab39001159d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='APELLIDO PATERNO'])[1]/following::small[2]</value>
      <webElementGuid>3943076d-b8e9-4d8f-bb8a-c3ee46aa17a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aceptar']/parent::*</value>
      <webElementGuid>7f958e65-2774-4a74-a127-662af39f7735</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//app-validacion-apellido-modal/div/div/div[3]/div[2]/small</value>
      <webElementGuid>48d37bb6-7d59-4b16-8783-01325248c7e6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[(text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>9ff44bb7-fb15-4c25-b277-789d100537a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//small[@id='aceptarCargoAdjunto']</value>
      <webElementGuid>0cb02f85-ecb8-4242-956f-a03e836d464f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='content']/main/app-formulario-envio/app-cargo-adjunto/div/div/div[5]/div[2]/small[2]</value>
      <webElementGuid>6f107acd-1554-437f-be0c-e694791afdd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INGRESE EL DESTINO DEL CARGO'])[1]/following::small[2]</value>
      <webElementGuid>adf29078-3846-4e58-939d-be76cdb2008b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'aceptarCargoAdjunto', '&quot;', ')')])[1]/preceding::small[1]</value>
      <webElementGuid>38729bcf-cb5a-42de-8a68-5c00f5c5c2b4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/small[2]</value>
      <webElementGuid>195e46ae-397c-4ca6-9c72-1d311287ea68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//small[@id = 'aceptarCargoAdjunto' and (text() = 'Aceptar' or . = 'Aceptar')]</value>
      <webElementGuid>8da3075e-fe6a-48c3-b70c-66ce64077d15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='REFERENCIA'])[1]/following::small[2]</value>
      <webElementGuid>899c919d-47ff-49ff-ab1f-194740c12bdb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
